export type CognitiveMechanic={
  id:string;
  titleRu:string;
  titleKk:string;
  skill:string;
  category:'spatial'|'memory'|'attention'|'inhibition'|'flexibility'|'processing'|'reaction'|'dual'|'patterns'|'planning';
  taskType:string;
  measures:string[];
  minDifficulty:number;
  maxDifficulty:number;
  keywords:RegExp;
};

export type CognitiveGeneratedTask={dayIndex:number;orderIndex:number;subject:string;skill:string;grade:number;difficulty:number;prompt:string;options:string[];correctOption:number;hint:string;explanation:string;xpReward:number;taskType?:string;metadata?:Record<string,unknown>};

export const cognitiveMechanics: CognitiveMechanic[]=[
  {id:'puzzle-4',titleRu:'Пазл 2×2',titleKk:'2×2 пазл',skill:'Визуально-пространственное мышление',category:'spatial',taskType:'puzzle',measures:['completionTime','mistakes','interactionCount','firstActionLatency'],minDifficulty:1,maxDifficulty:2,keywords:/простран|пазл|spatial|геометр/i},
  {id:'puzzle-rotated',titleRu:'Пазл с поворотом',titleKk:'Бұрылған пазл',skill:'Мысленное вращение',category:'spatial',taskType:'rotated-puzzle',measures:['completionTime','wrongMoves','rotations','pauses'],minDifficulty:2,maxDifficulty:4,keywords:/простран|поворот|геометр|spatial/i},
  {id:'picture-memory',titleRu:'Картинка по памяти',titleKk:'Суретті есте сақтау',skill:'Визуальная память',category:'memory',taskType:'picture-memory',measures:['recallAccuracy','firstActionLatency','completionTime'],minDifficulty:1,maxDifficulty:4,keywords:/память|memory|жады|есте/i},
  {id:'grid-memory-3',titleRu:'Запомни клетки 3×3',titleKk:'3×3 ұяшықтарды есте сақта',skill:'Пространственная память',category:'memory',taskType:'grid-memory',measures:['correctCells','omissions','falsePositives','reactionTime'],minDifficulty:1,maxDifficulty:3,keywords:/память|memory|зейін|attention/i},
  {id:'grid-memory-5',titleRu:'Запомни клетки 5×5',titleKk:'5×5 ұяшықтарды есте сақта',skill:'Пространственная память',category:'memory',taskType:'grid-memory',measures:['correctCells','omissions','falsePositives','completionTime'],minDifficulty:3,maxDifficulty:5,keywords:/память|memory|простран|spatial/i},
  {id:'simon-sequence',titleRu:'Повтори последовательность',titleKk:'Реттілікті қайтала',skill:'Рабочая память',category:'memory',taskType:'sequence-repeat',measures:['sequenceLength','accuracy','reactionTimeStd'],minDifficulty:1,maxDifficulty:5,keywords:/память|working|жады|рет/i},
  {id:'reverse-sequence',titleRu:'Обратная последовательность',titleKk:'Кері реттілік',skill:'Рабочая память + контроль',category:'memory',taskType:'reverse-sequence',measures:['sequenceLength','accuracy','mistakes'],minDifficulty:2,maxDifficulty:5,keywords:/память|контроль|жады|кері/i},
  {id:'odd-object',titleRu:'Найди отличие',titleKk:'Айырмашылықты тап',skill:'Визуальный поиск',category:'attention',taskType:'odd-one-out',measures:['reactionTime','accuracy','misses'],minDifficulty:1,maxDifficulty:4,keywords:/фокус|вним|attention|іздеу/i},
  {id:'memory-pairs',titleRu:'Найди пары',titleKk:'Жұптарды тап',skill:'Визуальная память',category:'memory',taskType:'memory-pairs',measures:['turns','mistakes','completionTime'],minDifficulty:1,maxDifficulty:4,keywords:/память|пары|жұп|memory/i},
  {id:'pattern-next',titleRu:'Найди закономерность',titleKk:'Заңдылықты тап',skill:'Pattern Recognition',category:'patterns',taskType:'pattern-next',measures:['accuracy','responseTime','ruleTransfer'],minDifficulty:1,maxDifficulty:5,keywords:/законом|паттерн|pattern|логик/i},
  {id:'what-changed',titleRu:'Что изменилось?',titleKk:'Не өзгерді?',skill:'Зрительная память',category:'memory',taskType:'change-detection',measures:['changeType','accuracy','reactionTime'],minDifficulty:2,maxDifficulty:5,keywords:/память|вним|memory|attention/i},
  {id:'extra-object',titleRu:'Лишний объект',titleKk:'Артық объект',skill:'Категоризация',category:'patterns',taskType:'categorization',measures:['accuracy','reasonChoice','responseTime'],minDifficulty:1,maxDifficulty:4,keywords:/классиф|анализ|logic|логик/i},
  {id:'symbol-search',titleRu:'Поиск символа',titleKk:'Символды іздеу',skill:'Избирательное внимание',category:'attention',taskType:'symbol-search',measures:['hits','misses','falsePositives','reactionTrend'],minDifficulty:1,maxDifficulty:5,keywords:/фокус|вним|attention|сигнал/i},
  {id:'cpt-target',titleRu:'Continuous Performance',titleKk:'Тұрақты реакция',skill:'Устойчивое внимание',category:'attention',taskType:'cpt',measures:['accuracyTimeline','omissions','falsePositives','stableTimePercent'],minDifficulty:2,maxDifficulty:5,keywords:/устойчив|фокус|attention|focus/i},
  {id:'sustained-focus',titleRu:'Устойчивый фокус',titleKk:'Тұрақты фокус',skill:'Sustained Attention',category:'attention',taskType:'sustained-focus',measures:['reactionSlope','errorSlope','fatigueMarkers'],minDifficulty:2,maxDifficulty:5,keywords:/устойчив|утом|fatigue|focus/i},
  {id:'go-no-go',titleRu:'Go / No-Go',titleKk:'Go / No-Go',skill:'Контроль импульса',category:'inhibition',taskType:'go-no-go',measures:['falsePositives','reactionTime','inhibitionAccuracy'],minDifficulty:1,maxDifficulty:5,keywords:/импульс|контроль|reaction|тормож/i},
  {id:'stop-signal',titleRu:'STOP Signal',titleKk:'STOP сигналы',skill:'Остановка действия',category:'inhibition',taskType:'stop-signal',measures:['stopAccuracy','lateStops','reactionTime'],minDifficulty:3,maxDifficulty:5,keywords:/импульс|контроль|stop|тормож/i},
  {id:'stroop-color',titleRu:'Stroop',titleKk:'Stroop',skill:'Торможение автоматического ответа',category:'inhibition',taskType:'stroop',measures:['stroopCost','accuracy','reactionTime'],minDifficulty:2,maxDifficulty:5,keywords:/импульс|спеш|контроль|stroop/i},
  {id:'rule-switch',titleRu:'Меняющееся правило',titleKk:'Ауыспалы ереже',skill:'Когнитивная гибкость',category:'flexibility',taskType:'rule-switch',measures:['firstSwitchError','adaptationTime','switchErrors'],minDifficulty:2,maxDifficulty:5,keywords:/переключ|flex|ереже|гибк/i},
  {id:'dual-rule',titleRu:'Двойное правило',titleKk:'Қос ереже',skill:'Удержание двух правил',category:'flexibility',taskType:'dual-rule',measures:['accuracy','ruleConflictErrors','reactionTime'],minDifficulty:3,maxDifficulty:5,keywords:/переключ|двой|flex|ереже/i},
  {id:'fast-classification',titleRu:'Быстрая классификация',titleKk:'Жылдам сұрыптау',skill:'Скорость обработки',category:'processing',taskType:'fast-classification',measures:['medianReactionTime','bestReactionTime','reactionTimeStd'],minDifficulty:1,maxDifficulty:5,keywords:/скорость|processing|өңдеу|жылдам/i},
  {id:'reaction-random',titleRu:'Реакция на появление',titleKk:'Пайда болуға реакция',skill:'Reaction Time',category:'reaction',taskType:'reaction-test',measures:['medianReactionTime','bestReactionTime','earlyClicks','reactionTimeStd'],minDifficulty:1,maxDifficulty:5,keywords:/reaction|реакц|жылдам|скор/i},
  {id:'mental-rotation',titleRu:'Поворот фигуры',titleKk:'Фигураны бұру',skill:'Ментальное вращение',category:'spatial',taskType:'mental-rotation',measures:['accuracy','rotationAngle','responseTime'],minDifficulty:2,maxDifficulty:5,keywords:/простран|поворот|геометр|spatial/i},
  {id:'maze-route',titleRu:'Лабиринт',titleKk:'Лабиринт',skill:'Планирование маршрута',category:'planning',taskType:'maze',measures:['pathLength','wrongTurns','backtracks','completionTime'],minDifficulty:2,maxDifficulty:5,keywords:/маршрут|лабиринт|planning|простран/i},
  {id:'shape-builder',titleRu:'Собери фигуру',titleKk:'Фигура құрастыр',skill:'Конструктор формы',category:'spatial',taskType:'shape-builder',measures:['completionTime','wrongMoves','interactionCount'],minDifficulty:1,maxDifficulty:5,keywords:/пазл|сбор|құрастыр|конструктор|spatial/i},
  {id:'dual-task',titleRu:'Dual Task',titleKk:'Қос тапсырма',skill:'Двойное внимание',category:'dual',taskType:'dual-task',measures:['visualHits','audioHits','dualCost','omissions'],minDifficulty:3,maxDifficulty:5,keywords:/двой|dual|вним|attention/i},
  {id:'audio-visual-bind',titleRu:'Звук + символ',titleKk:'Дыбыс + символ',skill:'Мультимодальная память',category:'dual',taskType:'audio-visual',measures:['bindingAccuracy','reactionTime','misses'],minDifficulty:2,maxDifficulty:5,keywords:/звук|дыбыс|dual|память/i},
  {id:'body-balance-count',titleRu:'Баланс + счёт',titleKk:'Баланс + санау',skill:'Мозг + тело',category:'dual',taskType:'motor-cognitive',measures:['completionTime','accuracy','selfRegulation'],minDifficulty:1,maxDifficulty:3,keywords:/баланс|координац|тело|дене|утом/i},
  {id:'clap-inhibition',titleRu:'Хлопки по правилу',titleKk:'Ереже бойынша шапалақ',skill:'Импульс + правило',category:'inhibition',taskType:'motor-inhibition',measures:['ruleErrors','falsePositives','reactionTime'],minDifficulty:1,maxDifficulty:4,keywords:/хлоп|шапалақ|импульс|контроль/i},
  {id:'mini-code-order',titleRu:'Мини-код',titleKk:'Мини-код',skill:'Алгоритмическое мышление',category:'planning',taskType:'code-order',measures:['orderAccuracy','planningTime','mistakes'],minDifficulty:1,maxDifficulty:5,keywords:/код|алгоритм|code|робот/i}
];

const pick=(items:string[],seed:number)=>items[Math.abs(seed)%items.length];
const chooseOptions=(options:string[],correct:number,seed:number)=>{const shift=Math.abs(seed)%options.length,rotated=[...options.slice(shift),...options.slice(0,shift)];return{options:rotated,correctOption:rotated.indexOf(options[correct])}};

export function selectCognitiveMechanic(day:number,order:number,difficulty:number,neuroSkills:string[]=[]){
  const preferred=cognitiveMechanics.filter(item=>neuroSkills.some(skill=>item.keywords.test(skill)));
  const pool=preferred.length?preferred:cognitiveMechanics;
  const filtered=pool.filter(item=>difficulty>=item.minDifficulty&&difficulty<=item.maxDifficulty);
  return (filtered.length?filtered:pool)[Math.abs(day*7+order*11+difficulty*13)%((filtered.length?filtered:pool).length)];
}

export function generateCognitiveMechanicTask(day:number,order:number,grade:number,language:'ru'|'kk',neuroSkills:string[]=[]):CognitiveGeneratedTask{
  const kk=language==='kk',difficulty=Math.max(1,Math.min(5,day<2?1:day<5?2:3+(grade>=7?1:0))),mechanic=selectCognitiveMechanic(day,order,difficulty,neuroSkills),subject=kk?'Ми жаттығуы':'Нейроразминка',seed=day*31+order*17+grade*5;
  const common={dayIndex:day,orderIndex:order,subject,grade,difficulty,skill:kk?mechanic.titleKk:mechanic.titleRu,xpReward:14+difficulty*2,taskType:mechanic.taskType,metadata:{mechanicId:mechanic.id,category:mechanic.category,measures:mechanic.measures,difficultyLevel:difficulty}};
  const task=(()=>{
    if(mechanic.taskType.includes('puzzle')||mechanic.taskType==='shape-builder'){const variants=kk?['A–B–C–D','A–C–B–D','B–A–D–C','C–D–A–B']:['A–B–C–D','A–C–B–D','B–A–D–C','C–D–A–B'],set=chooseOptions(variants,0,seed);return{prompt:kk?'2×2 суретті жол бойынша құрастыр: A жоғары-сол, B жоғары-оң, C төмен-сол, D төмен-оң. Дұрыс рет?':'Собери 2×2 картинку по строкам: A верх-лево, B верх-право, C низ-лево, D низ-право. Какой порядок правильный?',...set,hint:kk?'Алдымен жоғарғы қатар, кейін төменгі қатар.':'Сначала верхний ряд, затем нижний.',explanation:kk?'Дұрыс рет — A–B–C–D.':'Правильный порядок — A–B–C–D.'}}
    if(mechanic.taskType.includes('memory')||mechanic.taskType==='sequence-repeat'||mechanic.taskType==='reverse-sequence'||mechanic.taskType==='memory-pairs'){const seq=[2+seed%7,4+(seed+1)%6,1+(seed+3)%8,5+(seed+5)%5],reverse=mechanic.taskType==='reverse-sequence',correct=reverse?[...seq].reverse().join('–'):String(seq[2]),options=reverse?[seq.join('–'),[...seq].reverse().join('–'),[seq[3],seq[1],seq[2],seq[0]].join('–'),[seq[1],seq[0],seq[3],seq[2]].join('–')]:seq.map(String),set=chooseOptions(options,reverse?1:2,seed);return{prompt:reverse?(kk?`Қатарды кері ретпен таңда: ${seq.join('–')}`:`Выбери ряд в обратном порядке: ${seq.join('–')}`):(kk?`Қатарды есте сақта: ${seq.join('–')}. Үшінші сан қандай?`:`Запомни ряд: ${seq.join('–')}. Какая цифра была третьей?`),...set,hint:kk?'Ақпаратты қысқа уақыт ұстап тұр.':'Удержи информацию несколько секунд.',explanation:reverse?(kk?'Кері реттілік соңғы элементтен басталады.':'Обратный ряд начинается с последнего элемента.'):(kk?`Үшінші сан — ${seq[2]}.`:`Третье число — ${seq[2]}.`)}}
    if(mechanic.category==='attention'){const target=pick(['★','●','▲','■'],seed),noise=pick(['○','△','□','◆'],seed+1),row=[target,noise,target,'7',noise,target,'A',target].join(' '),set=chooseOptions(['2','3','4','5'],3,seed);return{prompt:kk?`Мақсатты ғана сана: ${row}. ${target} қанша?`:`Считай только цель: ${row}. Сколько символов ${target}?`,...set,hint:kk?'Бір ғана мақсатты ұста.':'Держи одну цель и игнорируй помехи.',explanation:kk?`${target} төрт рет кездеседі.`:`${target} встречается четыре раза.`}}
    if(mechanic.category==='inhibition'){const set=chooseOptions(kk?['қызыл','көк','жасыл','сары']:['красный','синий','зелёный','жёлтый'],1,seed);return{prompt:kk?'Stroop: сөз «ҚЫЗЫЛ», бірақ түсі көк. Сөзді емес, түсті таңда.':'Stroop: слово «КРАСНЫЙ», но цвет текста — синий. Выбери цвет, а не слово.',...set,hint:kk?'Автоматты оқуды тоқтат.':'Останови автоматическое чтение.',explanation:kk?'Түс — көк.':'Цвет — синий.'}}
    if(mechanic.category==='flexibility'){const n=3+seed%7,answer=n%2===0?n+2:n-1,set=chooseOptions([String(answer),String(answer+1),String(Math.max(0,answer-2)),String(answer+3)],0,seed);return{prompt:kk?`Ереже ауысты: жұп санға +2, тақ санға −1. ${n} үшін жауап?`:`Правило меняется: чётное число → +2, нечётное → −1. Что получится для ${n}?`,...set,hint:kk?'Алдымен жұп/тақ екенін анықта.':'Сначала определи, чётное число или нечётное.',explanation:kk?`${n%2===0?'Жұп':'Тақ'} санға ереже қолданылды.`:`К числу применили правило ${n%2===0?'чётного':'нечётного'}.`}}
    if(mechanic.category==='reaction'||mechanic.category==='processing'){const a=4+seed%8,b=2+(seed+3)%7,answer=a+b,set=chooseOptions([String(answer),String(answer+1),String(answer-1),String(answer+3)],0,seed);return{prompt:kk?`Жылдам классификация: ${a} + ${b}. Дұрыс жауапты таңда.`:`Быстрая классификация: ${a} + ${b}. Выбери ответ.`,...set,hint:kk?'Тез, бірақ тексеріп жауап бер.':'Быстро, но с короткой проверкой.',explanation:`${a} + ${b} = ${answer}.`}}
    if(mechanic.category==='dual'){const set=chooseOptions(['3','4','5','6'],1,seed);return{prompt:kk?'Қос тапсырма: жұп сандарды сана және ▲ белгілерін елеме: 4 ▲ 7 8 ●. Жұп сан қанша?':'Dual Task: считай чётные числа и игнорируй символы: 4 ▲ 7 8 ●. Сколько чётных чисел?',...set,hint:kk?'Сандар бөлек, белгілер бөлек.':'Смотри только на числа, символы игнорируй.',explanation:kk?'Жұп сандар: 4 және 8.':'Чётные числа: 4 и 8.'}}
    if(mechanic.category==='planning'){const set=chooseOptions(['read → plan → solve → check','solve → read → check → plan','check → solve → read → plan','plan → check → read → solve'],0,seed);return{prompt:kk?'Мини-код тәртібін таңда: оқу, жоспарлау, шешу, тексеру.':'Выбери правильный порядок мини-кода: прочитать, спланировать, решить, проверить.',...set,hint:kk?'Алдымен түсіну, соңында тексеру.':'Сначала понять, в конце проверить.',explanation:kk?'Логика: read → plan → solve → check.':'Логика: read → plan → solve → check.'}}
    const set=chooseOptions(['▲','●','■','◆'],0,seed);return{prompt:kk?'Паттернді жалғастыр: ▲ ● ▲ ● ?':'Продолжи паттерн: ▲ ● ▲ ● ?',...set,hint:kk?'Фигуралар кезектеседі.':'Фигуры чередуются.',explanation:kk?'Келесі фигура — ▲.':'Следующая фигура — ▲.'};
  })();
  return{...common,...task};
}
