export type CognitiveCategory='attention'|'memory'|'logic'|'reaction'|'processing'|'spatial'|'patterns'|'analysis'|'learning'|'comprehension';
export type DiagnosticQuestion={id:string;section:'math'|'logic'|'language';skill:string;prompt:string;options:string[];correct:number;difficulty?:number;category?:CognitiveCategory;recommendedAgeRange?:[number,number];estimatedTime?:number;explanation?:string;learningGroup?:string};

const q=(id:string,section:DiagnosticQuestion['section'],skill:string,prompt:string,options:string[],correct:number):DiagnosticQuestion=>({id,section,skill,prompt,options,correct});

const gradeMath=(grade:number):DiagnosticQuestion[]=>{
  if(grade<=2)return [
    q('m1','math','Счёт','Какое число идёт после 39?',['38','40','49','41'],1),q('m2','math','Сложение','Сколько будет 17 + 8?',['23','24','25','26'],2),q('m3','math','Вычитание','Сколько будет 31 − 9?',['20','21','22','23'],2),q('m4','math','Сравнение','Какое число самое большое?',['46','64','54','44'],1),q('m5','math','Задачи','У Даны 12 карандашей, ей подарили ещё 5. Сколько стало?',['7','15','17','18'],2),q('m6','math','Геометрия','У какой фигуры три стороны?',['круг','квадрат','треугольник','прямоугольник'],2)
  ];
  if(grade<=4)return [
    q('m1','math','Вычисления','Сколько будет 248 + 157?',['395','405','415','505'],1),q('m2','math','Вычисления','Сколько будет 600 − 278?',['312','322','332','378'],1),q('m3','math','Умножение','Чему равно 8 × 7?',['48','54','56','64'],2),q('m4','math','Деление','Чему равно 72 ÷ 9?',['7','8','9','10'],1),q('m5','math','Задачи','В 6 коробках по 9 книг. Сколько книг всего?',['15','45','54','63'],2),q('m6','math','Геометрия','Периметр прямоугольника 6 × 4 равен…',['10','20','24','28'],1)
  ];
  if(grade<=7)return [
    q('m1','math','Целые числа','−12 + 19 = …',['−31','−7','7','31'],2),q('m2','math','Дроби','3/4 − 1/8 = …',['2/4','5/8','1/2','7/8'],1),q('m3','math','Проценты','35% от 200 равно…',['35','60','70','85'],2),q('m4','math','Уравнения','Решите: 4x − 7 = 21',['5','6','7','8'],2),q('m5','math','Пропорции','4 билета стоят 2400 ₸. Сколько стоят 7?',['3600 ₸','4000 ₸','4200 ₸','4800 ₸'],2),q('m6','math','Геометрия','Площадь треугольника с основанием 10 и высотой 6 равна…',['16','30','60','80'],1)
  ];
  if(grade<=9)return [
    q('m1','math','Алгебра','Раскройте скобки: 3(x + 2)',['3x + 2','3x + 5','3x + 6','6x'],2),q('m2','math','Квадратные корни','√144 = …',['11','12','14','72'],1),q('m3','math','Функции','Для y = 3x − 2 найдите y при x = 4.',['8','10','12','14'],1),q('m4','math','Системы','Если x + y = 10 и x = 4, то y = …',['4','5','6','14'],2),q('m5','math','Вероятность','В мешке 3 красных и 7 синих шаров. Вероятность красного…',['3/7','3/10','7/10','1/3'],1),q('m6','math','Геометрия','Гипотенуза при катетах 6 и 8 равна…',['10','12','14','48'],0)
  ];
  return [
    q('m1','math','Алгебра','Упростите: 2x² + 3x² − x²',['3x²','4x²','5x²','4x'],1),q('m2','math','Уравнения','Решите: x² − 9 = 0',['только 3','только −3','−3 и 3','0 и 9'],2),q('m3','math','Функции','Область определения 1/(x−2) исключает…',['−2','0','1','2'],3),q('m4','math','Тригонометрия','sin 30° равен…',['0','1/2','√2/2','1'],1),q('m5','math','Вероятность','Вероятность двух орлов при двух бросках монеты…',['1/2','1/3','1/4','3/4'],2),q('m6','math','Геометрия','Площадь круга радиуса 3 равна…',['3π','6π','9π','18π'],2)
  ];
};

const gradeLogic=(grade:number):DiagnosticQuestion[]=>grade<=4?[
  q('l1','logic','Последовательности','Продолжите ряд: 3, 6, 9, 12, …',['13','14','15','16'],2),q('l2','logic','Классификация','Какой предмет лишний?',['яблоко','груша','слива','стул'],3),q('l3','logic','Аналогии','Птица летает, а рыба…',['бежит','плавает','читает','спит'],1),q('l4','logic','Условия','Алия выше Даны. Кто ниже?',['Алия','Дана','одинаково','нельзя понять'],1),q('l5','logic','Пространство','Стрелку ↑ повернули вправо. Куда она смотрит?',['←','→','↓','↑'],1)
]:grade<=7?[
  q('l1','logic','Последовательности','Продолжите: 2, 6, 12, 20, …',['26','28','30','32'],2),q('l2','logic','Классификация','Какое понятие лишнее?',['метр','литр','килограмм','треугольник'],3),q('l3','logic','Аналогии','Термометр : температура = часы : …',['скорость','время','расстояние','масса'],1),q('l4','logic','Условия','Все A — B. Ни одно B не является C. Может ли A быть C?',['да, всегда','нет','иногда','данных нет'],1),q('l5','logic','Закономерности','Если 2→6, 3→12, 4→20, то 5→…',['25','28','30','35'],2)
]:[
  q('l1','logic','Последовательности','Продолжите: 1, 2, 6, 24, …',['48','96','120','144'],2),q('l2','logic','Логические связи','Если p → q и p истинно, то…',['q истинно','q ложно','p ложно','вывода нет'],0),q('l3','logic','Аналогии','Гипотеза : исследование = диагноз : …',['симптом','обследование','лекарство','врач'],1),q('l4','logic','Условия','Некоторые A — B. Все B — C. Что следует?',['Все A — C','Некоторые A — C','Ни одно A не C','Все C — A'],1),q('l5','logic','Комбинаторика','Сколько двузначных чисел можно составить из 1, 2, 3 без повторов?',['3','6','9','12'],1)
];

const gradeLanguage=(grade:number,language:'ru'|'kk'):DiagnosticQuestion[]=>{
  if(language==='kk'){
    if(grade<=4)return [q('k1','language','Сөз мағынасы','«Батыл» сөзіне мағыналас сөзді табыңыз.',['қорқақ','ержүрек','әлсіз','үнсіз'],1),q('k2','language','Көптік жалғауы','Дұрыс жазылған сөзді табыңыз.',['кітаплар','кітапдер','кітаптар','кітаплер'],2),q('k3','language','Сөйлем','«Оқушы кітап оқыды» сөйлеміндегі бастауыш…',['оқушы','кітап','оқыды','оқушы кітап'],0),q('k4','language','Емле','Дұрыс жазылған сөз…',['мұғалім','мұғалым','мүғалім','мұғәлім'],0),q('k5','language','Мәтінді түсіну','«Асан ерте тұрып, мектепке барды». Асан қайда барды?',['үйге','дүкенге','мектепке','саябаққа'],2),q('k6','language','Сөз таптары','«Әдемі» сөзі қай сөз табы?',['зат есім','сын есім','етістік','сан есім'],1)];
    if(grade<=7)return [q('k1','language','Лексика','«Қамқор» сөзіне мағыналас сөз…',['мейірімді','қатал','ұмытшақ','ашулы'],0),q('k2','language','Септік','«Мектепке» сөзі қай септікте?',['атау','барыс','табыс','жатыс'],1),q('k3','language','Етістік','Өткен шақтағы етістікті табыңыз.',['оқиды','оқыды','оқып отыр','оқыр'],1),q('k4','language','Құрмалас сөйлем','Құрмалас сөйлемді табыңыз.',['Күн шықты.','Балалар ойнады.','Күн шықты да, балалар далаға шықты.','Жылы күн.'],2),q('k5','language','Мәтінді түсіну','Мәтіннің негізгі ойын анықтау үшін ең маңыздысы…',['әріп санын санау','автордың не айтқысы келгенін түсіну','бірінші сөзді жаттау','соңғы сөйлемді көшіру'],1),q('k6','language','Тыныс белгісі','Қаратпа сөз дұрыс рәсімделген сөйлем…',['Асан бері кел.','Асан, бері кел.','Асан бері, кел.','Асан: бері кел.'],1)];
    return [q('k1','language','Лексика','Контексте «өзекті мәселе» тіркесі нені білдіреді?',['ескірген','маңызды әрі шешуді қажет ететін','оңай','жасырын'],1),q('k2','language','Синтаксис','Себеп бағыныңқылы сабақтасты табыңыз.',['Күн шықты, дала жылынды.','Жаңбыр жауғандықтан, жол суланды.','Ол келді де кетті.','Мен кітап оқыдым.'],1),q('k3','language','Стиль','Ғылыми стильдің негізгі белгісі…',['бейнелілік','дәлдік және терминдер','ауызекі сөздер','эмоциялық леп'],1),q('k4','language','Дәлел','Пікірді дәлелдеудің сенімді тәсілі…',['ойды қайталау','дерек пен мысал келтіру','ұзақ сөйлем жазу','сұрақ қою'],1),q('k5','language','Мәтін құрылымы','Аргументативті мәтіннің логикалық реті…',['қорытынды–тезис–мысал','тезис–дәлел–қорытынды','мысал–тақырып–сұрақ','сұрақ–қорытынды–тезис'],1),q('k6','language','Пунктуация','Жалпылауыш сөзден кейін бірыңғай мүшелер келсе…',['үтір','қос нүкте','нүкте','сұрау белгісі'],1)];
  }
  if(grade<=4)return [q('r1','language','Лексика','Синоним слова «смелый»…',['трусливый','храбрый','тихий','слабый'],1),q('r2','language','Орфография','В каком слове нет ошибки?',['интиресный','интересный','интерестный','интирестный'],1),q('r3','language','Грамматика','Подлежащее: «Ученик читает книгу».',['ученик','читает','книгу','читает книгу'],0),q('r4','language','Части речи','Слово «быстро» — это…',['существительное','прилагательное','наречие','глагол'],2),q('r5','language','Понимание текста','«После дождя дети увидели радугу». Что они увидели?',['дождь','солнце','радугу','облако'],2),q('r6','language','Пунктуация','Правильное предложение…',['Мама сказала «Пора домой».','Мама сказала: «Пора домой».','Мама, сказала: «Пора домой».','Мама сказала «Пора, домой».'],1)];
  if(grade<=7)return [q('r1','language','Лексика','Антоним слова «искренний»…',['честный','открытый','лицемерный','добрый'],2),q('r2','language','Орфография','Выберите правильное написание.',['не смотря на дождь','несмотря на дождь','не-смотря на дождь','несмотря над дождём'],1),q('r3','language','Грамматика','В предложении «Река медленно замерзала» сказуемое…',['река','медленно','замерзала','медленно замерзала'],2),q('r4','language','Причастие','Найдите причастие.',['читающий','читать','читал','чтение'],0),q('r5','language','Понимание текста','Главная мысль текста — это…',['первое слово','то, что автор хочет донести','самое длинное предложение','имя героя'],1),q('r6','language','Пунктуация','Где нужна запятая: «Когда стемнело мы вернулись».',['после «когда»','после «стемнело»','после «мы»','не нужна'],1)];
  return [q('r1','language','Лексика','«Актуальная проблема» означает…',['устаревшая','важная в настоящее время','простая','неразрешимая'],1),q('r2','language','Синтаксис','Какое придаточное в «Я знаю, что экзамен состоится»?',['определительное','изъяснительное','условия','причины'],1),q('r3','language','Стиль','Для научного стиля характерны…',['разговорные слова','точность и термины','эмоциональные восклицания','сюжетность'],1),q('r4','language','Аргументация','Сильнее всего подтверждает тезис…',['повтор тезиса','проверяемый факт и объяснение','риторический вопрос','длинное вступление'],1),q('r5','language','Структура текста','Логичная структура рассуждения…',['вывод–тезис–пример','тезис–аргумент–вывод','пример–вывод–вопрос','описание–диалог–заголовок'],1),q('r6','language','Пунктуация','В бессоюзном предложении причина после первой части часто отделяется…',['запятой','двоеточием','точкой с запятой','скобками'],1)];
};

const cognitionMeta:Record<string,{category:CognitiveCategory;explanation:string}>={
  'Счёт':{category:'processing',explanation:'Нужно быстро обработать числовую информацию.'},'Вычисления':{category:'processing',explanation:'Проверяется точность последовательных вычислений.'},'Сложение':{category:'processing',explanation:'Применяется правило сложения.'},'Вычитание':{category:'processing',explanation:'Применяется правило вычитания.'},'Умножение':{category:'memory',explanation:'Используется знание числовых фактов и рабочая память.'},'Деление':{category:'analysis',explanation:'Нужно выбрать обратную арифметическую операцию.'},'Задачи':{category:'comprehension',explanation:'Важно выделить данные и нужное действие.'},'Геометрия':{category:'spatial',explanation:'Проверяется работа с формой, размером и пространственными отношениями.'},'Пространство':{category:'spatial',explanation:'Мысленно поверните объект и проследите направление.'},'Пространственное мышление':{category:'spatial',explanation:'Мысленно поверните объект и проследите направление.'},'Последовательности':{category:'patterns',explanation:'Нужно определить правило изменения элементов.'},'Закономерности':{category:'patterns',explanation:'Правильный ответ следует из общего правила последовательности.'},'Классификация':{category:'analysis',explanation:'Нужно найти общий признак и исключение.'},'Аналогии':{category:'logic',explanation:'Сравниваются отношения между двумя парами понятий.'},'Условия':{category:'logic',explanation:'Вывод должен следовать только из данных условия.'},'Понимание текста':{category:'comprehension',explanation:'Ответ прямо следует из смысла прочитанного.'},'Мәтінді түсіну':{category:'comprehension',explanation:'Жауап мәтіннің мағынасынан шығады.'}
};
const cognitiveExtras=(grade:number,language:'ru'|'kk'):DiagnosticQuestion[]=>{
  const level=Math.max(1,Math.min(5,Math.ceil(grade/2.2))),ages:[number,number]=[Math.max(6,grade+5),Math.min(18,grade+8)],ru=language==='ru';
  const add=(id:string,section:DiagnosticQuestion['section'],skill:string,prompt:string,options:string[],correct:number,category:CognitiveCategory,difficulty=level,explanation='Ответ определяется правилом задания.',learningGroup?:string):DiagnosticQuestion=>({id,section,skill,prompt,options,correct,category,difficulty,recommendedAgeRange:ages,estimatedTime:category==='reaction'?12:35,explanation,learningGroup});
  return [
    add('cx-att-1','logic','Избирательное внимание',ru?'Сколько раз встречается буква «А»: А Б А В А Г Б А?':'«А» әрпі неше рет кездеседі: А Б А В А Г Б А?',['2','3','4','5'],2,'attention',Math.max(1,level-1),'Нужно последовательно просмотреть все символы и посчитать только целевой.'),
    add('cx-mem-1','logic','Рабочая память',ru?'Запомните: 7–2–9–4. Какая цифра была третьей?':'Есте сақтаңыз: 7–2–9–4. Үшінші сан қайсы?',['2','4','7','9'],3,'memory',level,'Третьим элементом последовательности была цифра 9.'),
    add('cx-react-1','logic','Скорость реакции',ru?'Какой символ отличается: ● ● ● ○ ●?':'Қай белгі өзгеше: ● ● ● ○ ●?',['1-й','2-й','4-й','5-й'],2,'reaction',Math.max(1,level-1),'Четвёртый символ отличается заливкой.'),
    add('cx-spatial-1','logic','Мысленное вращение',ru?'Стрелка смотрит вправо. После двух поворотов на 90° влево она смотрит…':'Жебе оңға қарап тұр. 90° солға екі рет бұрғанда…',['вверх','вниз','влево','вправо'],2,'spatial',level,'Два поворота по 90° дают разворот на 180°.'),
    add('cx-pattern-1','logic','Закономерности',ru?'Продолжите: ▲, ▲●, ▲●●, ▲●●●, …':'Жалғастырыңыз: ▲, ▲●, ▲●●, ▲●●●, …',['▲▲','▲●●●●','●▲●','▲●'],1,'patterns',level,'На каждом шаге добавляется один круг.'),
    add('cx-process-1','math','Скорость обработки',ru?'Какое выражение больше остальных?':'Қай өрнек басқаларынан үлкен?',['12+8','25−4','3×6','40÷2'],1,'processing',level,'Значения равны 20, 21, 18 и 20; наибольшее значение даёт 25−4.'),
    add('cx-analysis-1','logic','Аналитическое мышление',ru?'У всех синих карточек есть звезда. На карточке нет звезды. Что можно заключить?':'Барлық көк карточкада жұлдыз бар. Карточкада жұлдыз жоқ. Қорытынды?',['она синяя','она не синяя','она круглая','ничего'],1,'analysis',Math.min(5,level+1),'Если у всех синих есть звезда, отсутствие звезды исключает синий цвет.'),
    add('cx-learn-rule','language','Новое правило',ru?'Новое правило: знак ⊕ означает «прибавь 3». Чему равно 5 ⊕?':'Жаңа ереже: ⊕ «3-ті қос» дегенді білдіреді. 5 ⊕ нешеге тең?',['2','5','8','15'],2,'learning',level,'По новому правилу к 5 нужно прибавить 3.','plus3'),
    add('cx-learn-transfer','language','Перенос правила',ru?'Используйте то же правило ⊕. Чему равно 11 ⊕?':'Сол ⊕ ережесін қолданыңыз. 11 ⊕ нешеге тең?',['8','11','14','33'],2,'learning',Math.min(5,level+1),'То же правило переносится на новое число: 11 + 3 = 14.','plus3'),
    add('cx-comprehend-1','language','Понимание информации',ru?'Правило: вход разрешён только с карточкой. У Леи карточки нет. Что следует?':'Ереже: тек карточкамен кіруге болады. Леяда карточка жоқ. Не шығады?',['она войдёт','она не может войти по правилу','она сотрудник','данных нет'],1,'comprehension',level,'Без карточки условие входа не выполнено.')
  ];
};

const enrich=(item:DiagnosticQuestion,grade:number,index:number):DiagnosticQuestion=>{const meta=cognitionMeta[item.skill]||{category:item.section==='logic'?'logic':item.section==='math'?'processing':'comprehension',explanation:'Правильный ответ следует из правила и условий задания.'},start=Math.max(1,Math.min(5,Math.ceil(grade/2.2))),spread=((index*7)%3)-1;return{...item,id:`${item.id}-${grade}-${index}`,category:item.category||meta.category,difficulty:item.difficulty||Math.max(1,Math.min(5,start+spread)),recommendedAgeRange:item.recommendedAgeRange||[Math.max(6,grade+5),Math.min(18,grade+8)],estimatedTime:item.estimatedTime||Math.max(20,28+(item.difficulty||start+spread)*6),explanation:item.explanation||meta.explanation}};
const shuffle=<T,>(items:T[],seed:number)=>{const copy=[...items];for(let i=copy.length-1;i>0;i--){seed=(seed*9301+49297)%233280;const j=Math.floor(seed/233280*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]]}return copy};
const optionNumbers=(correct:number,seed:number)=>{const values=[correct,correct+(seed%3)+1,Math.max(0,correct-((seed%4)+1)),correct+5+(seed%5)],unique=[...new Set(values)].slice(0,4);while(unique.length<4)unique.push(correct+unique.length+7);const shift=seed%4,options=[...unique.slice(shift),...unique.slice(0,shift)];return{options:options.map(String),correct:options.indexOf(correct)}};
const dynamicPuzzles=(grade:number,language:'ru'|'kk',seed:number):DiagnosticQuestion[]=>{
  const ru=language==='ru',level=Math.max(1,Math.min(5,Math.ceil(grade/2.2))),n=seed%9+2,a=grade*3+seed%17+8,b=seed%8+3,sum=optionNumbers(a+b,seed),diff=optionNumbers(Math.max(0,a-b),seed+3),mul=optionNumbers((n%6+2)*(grade<=4?3:grade<=7?4:5),seed+7),shape=['▲','●','■','◆'][seed%4],other=['○','△','□','◇'][(seed+1)%4],count=3+seed%3,pattern=Array.from({length:7},(_,i)=>i%2===0?shape:other).join(' '),targetCount=4,rotate=['↑','→','↓','←'],start=seed%4,turns=1+seed%3,rotated=rotate[(start+turns)%4],memory=[seed%9+1,(seed+2)%9+1,(seed+5)%9+1,(seed+7)%9+1],third=memory[2];
  const mk=(id:string,section:DiagnosticQuestion['section'],skill:string,prompt:string,options:string[],correct:number,category:CognitiveCategory,difficulty=level,explanation='Ответ получается из правила пазла.'):DiagnosticQuestion=>({id,section,skill,prompt,options,correct,category,difficulty,recommendedAgeRange:[Math.max(6,grade+5),Math.min(18,grade+8)],estimatedTime:category==='reaction'?14:32,explanation});
  return [
    mk(`dyn-math-sum-${seed%997}`,'math','Визуальный счёт',ru?`Пазл с жетонами: в первой зоне ${a} точек, во второй ${b}. Сколько всего точек?`:`Таңба пазлы: бірінші аймақта ${a} нүкте, екіншісінде ${b}. Барлығы қанша?`,sum.options,sum.correct,'processing',level,'Нужно сложить количество в двух зонах.'),
    mk(`dyn-math-diff-${seed%991}`,'math','Ментальная арифметика',ru?`Робот собрал ${a} деталей и потратил ${b}. Сколько осталось?`:`Робот ${a} бөлшек жинап, ${b} бөлшек қолданды. Қанша қалды?`,diff.options,diff.correct,'processing',level,'Это короткая задача на удержание условия и вычитание.'),
    mk(`dyn-math-grid-${seed%983}`,'math','Паттерн-сетка',ru?`В каждом ряду по ${n%6+2} клетки, рядов ${grade<=4?3:grade<=7?4:5}. Сколько клеток в сетке?`:`Әр қатарда ${n%6+2} ұяшық, қатар саны ${grade<=4?3:grade<=7?4:5}. Барлығы қанша?`,mul.options,mul.correct,'spatial',Math.min(5,level+1),'Сетка считается как одинаковые группы.'),
    mk(`dyn-att-${seed%977}`,'logic','Визуальный поиск',ru?`Найди цель среди помех: ${pattern}. Сколько символов ${shape}?`:`Кедергілер арасынан мақсатты тап: ${pattern}. ${shape} қанша?`,['2','3','4','5'],targetCount-2,'attention',level,'Целевой символ стоит на позициях 1, 3, 5 и 7.'),
    mk(`dyn-memory-${seed%971}`,'logic','Рабочая память',ru?`Удержи ряд: ${memory.join('–')}. Какая цифра была третьей?`:`Қатарды есте сақта: ${memory.join('–')}. Үшінші сан қандай?`,[String(memory[0]),String(memory[1]),String(third),String(memory[3])],2,'memory',level,'Третьим элементом был третий символ исходного ряда.'),
    mk(`dyn-rotate-${seed%967}`,'logic','Мысленное вращение',ru?`Стрелка ${rotate[start]} повернулась вправо ${turns} раз(а). Куда она смотрит?`:`Жебе ${rotate[start]} оңға ${turns} рет бұрылды. Қайда қарайды?`,rotate,rotate.indexOf(rotated),'spatial',Math.min(5,level+1),'Каждый поворот вправо смещает направление на 90 градусов.'),
    mk(`dyn-puzzle-order-${seed%929}`,'logic','Сборка пазла',ru?'Собери 2×2 пазл по строкам. Детали: A = верх слева, B = верх справа, C = низ слева, D = низ справа. Какой порядок правильный?':'2×2 пазлды жол бойынша құрастыр. A = жоғары сол, B = жоғары оң, C = төмен сол, D = төмен оң. Дұрыс рет?',ru?['A–B–C–D','A–C–B–D','B–A–D–C','C–D–A–B']:['A–B–C–D','A–C–B–D','B–A–D–C','C–D–A–B'],0,'spatial',level,'Пазл читается по строкам: сначала верхняя, затем нижняя.'),
    mk(`dyn-puzzle-missing-${seed%919}`,'logic','Недостающий фрагмент',ru?'Пазл: верхний ряд ▲ ●, нижний ряд ■ ?. Во втором столбце нужна круглая форма. Какой фрагмент подходит?':'Пазл: жоғарғы қатар ▲ ●, төменгі қатар ■ ?. Екінші бағанда дөңгелек пішін керек. Қай бөлік сәйкес?',['◆','●','▲','■'],1,'patterns',level,'Нужна круглая форма во втором столбце, значит подходит ●.'),
    mk(`dyn-puzzle-layer-${seed%911}`,'logic','Порядок фрагментов',ru?'Картинка собирается слоями: фон → дом → окно → крыша. Какой слой ставится первым?':'Сурет қабатпен құралады: фон → үй → терезе → шатыр. Бірінші қай қабат?',ru?['окно','крыша','фон','дом']:['терезе','шатыр','фон','үй'],2,'analysis',Math.max(1,level-1),'Сначала ставится базовый слой — фон.'),
    mk(`dyn-maze-code-${seed%859}`,'logic','Пазл-лабиринт',ru?'Собери путь робота: вперёд → вправо → вперёд → стоп. Какой мини-код подходит?':'Робот жолын құрастыр: алға → оңға → алға → тоқта. Қай мини-код сәйкес?',['forward → right → forward → stop','right → forward → stop → forward','forward → left → forward → stop','stop → forward → right → forward'],0,'spatial',level,'Нужно удержать маршрут и выбрать такой же порядок команд.'),
    mk(`dyn-story-code-${seed%857}`,'language','Код истории',ru?'Собери историю как код: герой видит проблему → пробует решение → проверяет результат. Что идёт вторым?':'Оқиғаны код сияқты жина: кейіпкер мәселені көреді → шешім көреді → нәтижені тексереді. Екінші не?',ru?['пробует решение','видит проблему','проверяет результат','делает вывод']:['шешім көреді','мәселені көреді','нәтижені тексереді','қорытынды жасайды'],0,'learning',level,'После обнаружения проблемы логично попробовать решение.'),
    mk(`dyn-card-memory-${seed%853}`,'logic','Память карточек',ru?'Карточки были: 🟣5, 🟢8, 🔵3, 🟡7. Какая цифра была на зелёной карточке?':'Карточкалар: 🟣5, 🟢8, 🔵3, 🟡7. Жасыл карточкада қандай сан болды?',['5','8','3','7'],1,'memory',level,'Нужно удержать связь цвета и числа.'),
    mk(`dyn-connect-cause-${seed%851}`,'logic','Соедини причина → действие',ru?'Причина: ребёнок спешит и часто меняет ответы. Какое действие лучше?':'Себеп: бала асығып, жауаптарын жиі өзгертеді. Қай әрекет жақсы?',ru?['ввести паузу 3 секунды перед ответом','ускорить таймер','убрать подсказки навсегда','дать больше шума']:['жауап алдында 3 секунд пауза жасау','таймерді тездету','көмекті мүлде алып тастау','көбірек шу қосу'],0,'reaction',level,'Пауза помогает остановить импульсивный ответ.'),
    mk(`dyn-code-bug-${seed%849}`,'logic','Найди ошибку в коде',ru?'Мини-код: read → solve → explain → solve. Какая ошибка?':'Мини-код: оқу → шешу → түсіндіру → шешу. Қандай қате бар?',ru?['solve повторяется лишний раз','read должен быть последним','explain нельзя использовать','ошибки нет']:['solve артық қайталанады','оқу соңында болуы керек','түсіндіру болмайды','қате жоқ'],0,'analysis',level,'Повтор solve в конце нарушает логичный порядок.'),
    mk(`dyn-dual-task-${seed%847}`,'logic','Двойная задача',ru?'Считай только чётные числа и не трогай символы: 4 ▲ 7 8 ● 9. Сколько чётных чисел?':'Тек жұп сандарды сана, белгілерді қоспа: 4 ▲ 7 8 ● 9. Жұп сан қанша?',['1','2','3','4'],1,'attention',level,'Чётные числа здесь 4 и 8.'),
    mk(`dyn-build-object-${seed%839}`,'logic','Конструктор формы',ru?'Собери объект: прямоугольник снизу + треугольник сверху. Что получилось?':'Объект құрастыр: төменде тік төртбұрыш + жоғарыда үшбұрыш. Не шықты?',ru?['дом','мяч','часы','река']:['үй','доп','сағат','өзен'],0,'spatial',level,'Прямоугольник похож на стены, треугольник — на крышу.'),
    mk(`dyn-pattern-build-${seed%829}`,'logic','Дострой паттерн',ru?'Продолжи сборку: 🧩1 🧩2 🧩1 🧩2 ?. Какой фрагмент нужен?':'Жинақты жалғастыр: 🧩1 🧩2 🧩1 🧩2 ?. Қай бөлік керек?',['🧩1','🧩2','🧩3','🧩4'],0,'patterns',level,'Фрагменты чередуются 1–2–1–2, значит дальше 1.'),
    mk(`dyn-rule-${seed%953}`,'logic','Переключение правила',ru?`Правило: если видишь ${shape}, прибавь 2; если ${other}, вычти 1. Что будет для ${shape} и числа ${count}?`:`Ереже: ${shape} болса +2; ${other} болса −1. ${shape} және ${count} үшін жауап?`,optionNumbers(count+2,seed+13).options,optionNumbers(count+2,seed+13).correct,'learning',level,'Нужно применить новое правило к указанному символу.'),
    mk(`dyn-stroop-${seed%907}`,'logic','Торможение импульса',ru?'Правило: выбирай не слово, а направление. Слово «ВЛЕВО» написано рядом со стрелкой →. Что выбрать?':'Ереже: сөзді емес, бағытты таңда. «СОЛҒА» сөзі → жебесімен тұр. Не таңдайсың?',['←','→','↑','↓'],1,'reaction',level,'Нужно остановить автоматическое чтение слова и выбрать направление стрелки.'),
    mk(`dyn-two-step-${seed%887}`,'logic','Двухшаговая инструкция',ru?'Сначала выбери фигуру без углов, затем цвет неба. Какой ответ подходит?':'Алдымен бұрышы жоқ пішінді, кейін аспан түсін таңда. Қай жауап дұрыс?',ru?['круг + синий','квадрат + синий','круг + зелёный','треугольник + красный']:['шеңбер + көк','шаршы + көк','шеңбер + жасыл','үшбұрыш + қызыл'],0,'comprehension',level,'Без углов — круг, цвет неба — синий.'),
    mk(`dyn-matrix-${seed%883}`,'logic','Матрица признаков',ru?'В строке меняется форма: круг → квадрат → круг → ?. Какая форма дальше?':'Қатарда пішін ауысады: шеңбер → шаршы → шеңбер → ?. Келесі пішін?',['квадрат','круг','треугольник','ромб'],0,'patterns',Math.min(5,level+1),'Формы чередуются: круг, квадрат, круг, квадрат.'),
    mk(`dyn-classify-${seed%881}`,'logic','Быстрая классификация',ru?'Что лишнее по главному признаку?':'Негізгі белгі бойынша қайсысы артық?',ru?['датчик','мотор','провод','яблоко']:['датчик','мотор','сым','алма'],3,'analysis',level,'Первые три относятся к техническим деталям, яблоко — нет.'),
    mk(`dyn-career-tech-${seed%879}`,'logic','Профориентационная проба',ru?'Тебе нужно быстро собрать прототип. Какой первый шаг разумнее?':'Жылдам прототип жасау керек. Ең дұрыс бірінші қадам?',ru?['понять задачу','выбрать случайную деталь','сразу спорить','ничего не менять']:['міндетті түсіну','кездейсоқ бөлшек таңдау','бірден дауласу','ештеңе өзгертпеу'],0,'learning',level,'В инженерной задаче сначала уточняют цель и ограничения.'),
    mk(`dyn-career-design-${seed%877}`,'language','UX-мышление',ru?'Пользователь не понял инструкцию. Что улучшить сначала?':'Қолданушы нұсқауды түсінбеді. Алдымен нені жақсартқан дұрыс?',ru?['сделать текст короче и понятнее','добавить шум','убрать кнопку','усложнить правило']:['мәтінді қысқа әрі түсінікті ету','шу қосу','батырманы алып тастау','ережені қиындату'],0,'comprehension',level,'Хороший интерфейс сначала делает действие понятным.'),
    mk(`dyn-career-data-${seed%863}`,'math','Аналитика данных',ru?'За 3 дня выполнено 4, 6 и 8 заданий. Какой вывод точнее?':'3 күнде 4, 6 және 8 тапсырма орындалды. Қай қорытынды дәлірек?',ru?['результат растёт','результат падает','данных нет','все одинаково']:['нәтиже өсіп жатыр','нәтиже төмендеп жатыр','дерек жоқ','бәрі бірдей'],0,'analysis',level,'Последовательность 4 → 6 → 8 показывает рост.'),
    mk(`dyn-lang-order-${seed%947}`,'language','Структура текста',ru?'Собери логичный порядок: 1) вывод 2) пример 3) тезис. Что идёт первым?':'Логикалық ретті тап: 1) қорытынды 2) мысал 3) тезис. Бірінші не келеді?',['вывод / қорытынды','пример / мысал','тезис','любое'],2,'comprehension',level,'В рассуждении сначала формулируется тезис.'),
    mk(`dyn-lang-instruction-${seed%941}`,'language','Понимание инструкции',ru?'Инструкция: выбери вариант, где есть цвет и форма. Какой подходит?':'Нұсқау: түс пен пішін бірге бар жауапты таңда. Қайсысы сәйкес?',['синий круг','быстро','три','после урока'],0,'comprehension',level,'«Синий круг» содержит и цвет, и форму.'),
    mk(`dyn-lang-analogy-${seed%937}`,'language','Смысловая аналогия',ru?'Мозг относится к мышлению, как сердце относится к…':'Ми ойлауға қатысты, жүрек неге қатысты?',['чтению','движению крови','рисованию','счёту'],1,'logic',level,'Сердце связано с движением крови.')
  ];
};
export function diagnosticQuestions(grade:number,language:'ru'|'kk',seed=Date.now()){
  const base=[...gradeMath(grade),...gradeLogic(grade),...gradeLanguage(grade,language),...cognitiveExtras(grade,language),...dynamicPuzzles(grade,language,seed)].map((item,index)=>enrich(item,grade,index));
  const cognitive=shuffle(base.filter(item=>item.id.startsWith('cx-')||item.id.startsWith('dyn-')),seed+41);
  const diverse=(items:DiagnosticQuestion[],count:number)=>{const result:DiagnosticQuestion[]=[],used=new Set<string>();for(const item of items){if(!used.has(item.category||'')){result.push(item);used.add(item.category||'')}if(result.length===count)return result}for(const item of items){if(!result.some(existing=>existing.id===item.id))result.push(item);if(result.length===count)break}return result};
  const selected=diverse(cognitive,24);
  const hasSection=(section:DiagnosticQuestion['section'])=>selected.some(item=>item.section===section);
  for(const section of ['math','logic','language'] as const)if(!hasSection(section)){
    const replacement=cognitive.find(item=>item.section===section&&!selected.some(existing=>existing.id===item.id));
    if(replacement)selected[selected.length-1]=replacement;
  }
  return selected;
}

export function scoreDiagnostic(grade:number,language:'ru'|'kk',answers:Record<string,number>){
  const questions=diagnosticQuestions(grade,language);const sections:any={math:{right:0,total:0},logic:{right:0,total:0},language:{right:0,total:0}};const skills=new Map<string,{right:number;total:number}>();
  for(const item of questions){const ok=answers[item.id]===item.correct;sections[item.section].total++;if(ok)sections[item.section].right++;const skill=skills.get(item.skill)||{right:0,total:0};skill.total++;if(ok)skill.right++;skills.set(item.skill,skill)}
  const percent=(right:number,total:number)=>Math.round(right/Math.max(1,total)*100);const sectionScores=Object.fromEntries(Object.entries(sections).map(([key,value]:any)=>[key,percent(value.right,value.total)]));const skillScores=Object.fromEntries([...skills].map(([key,value])=>[key,percent(value.right,value.total)]));const sorted=Object.entries(skillScores).sort((a,b)=>a[1]-b[1]);const gaps=sorted.filter(([,value])=>value<70).map(([key])=>key);const strengths=sorted.filter(([,value])=>value>=80).reverse().map(([key])=>key);const totalScore=percent(Object.values(sections).reduce((sum:number,item:any)=>sum+item.right,0),questions.length);
  const level=totalScore>=85?'высокий':totalScore>=65?'базовый устойчивый':totalScore>=45?'частично сформированный':'требующий поддержки';
  const recommendations=[`Стартовая точка: общий уровень — ${level}. Первые учебные цели: ${gaps.slice(0,2).join(' и ')||'углубление сильных навыков'}. Не прорабатывайте больше двух пробелов одновременно.`,sectionScores.math<70?'Математика: 2–3 коротких блока в неделю. Сначала преподаватель показывает алгоритм на одном примере, затем ученик решает 3 задания с подсказкой и 5 самостоятельно.':'Математика: переходите к нестандартным и многошаговым задачам; просите ученика объяснять ход решения вслух.',sectionScores.logic<70?'Логика: через день по 10 минут тренируйте последовательности, классификацию, аналогии и точное чтение условий. После ответа обязательно обсуждайте ход рассуждения.':'Логика: добавьте задачи с лишними данными, несколькими условиями и сравнением двух способов решения.',sectionScores.language<70?`${language==='kk'?'Қазақ тілі':'Русский язык'}: ежедневно 10–15 минут работайте с коротким текстом — чтение, выделение главной мысли, пересказ и ответы на три вопроса. Ошибочные правила закрепляйте отдельными мини-упражнениями.`:'Язык: развивайте аргументацию, письменное объяснение, словарный запас и работу с незнакомым текстом.',`Неделя 1: разобрать ошибки диагностики без выставления оценки, выяснить причину каждого ответа и закрепить базовые понятия.`,`Недели 2–3: чередовать объяснение, самостоятельную практику и короткую проверку. Переходить дальше после двух успешных выполнений навыка подряд.`,`Недели 4–5: применять навыки в смешанных заданиях и учебных ситуациях. Фиксировать не только правильность, но и самостоятельность решения.`,`Повторная диагностика через 4–6 недель: использовать новые задания по тем же навыкам. Прогресс считать устойчивым при результате от 70% и отсутствии систематической ошибки.`];
  return {sectionScores,skillScores,gaps,strengths,totalScore,recommendations};
}

export type DiagnosticResponseMeta={questionId:string;answer:number|null;responseTimeMs:number;changes:number;timeout:boolean;startedAt:string;answeredAt?:string;eeg?:{attention:number;focus:number;engagement:number;relaxation:number;signal:number;samples:number}};
export function scoreAdaptiveDiagnostic(questions:DiagnosticQuestion[],answers:Record<string,number>,responses:DiagnosticResponseMeta[]=[]){
  const responseMap=new Map(responses.map(item=>[item.questionId,item])),categories=new Map<CognitiveCategory,{points:number;max:number;right:number;total:number;time:number;expected:number;levels:number[]}>(),sections:Record<string,{points:number;max:number;right:number;total:number}>={math:{points:0,max:0,right:0,total:0},logic:{points:0,max:0,right:0,total:0},language:{points:0,max:0,right:0,total:0}},skills=new Map<string,{points:number;max:number;right:number;total:number}>();
  const review=questions.map((item,index)=>{const response=responseMap.get(item.id),answer=answers[item.id],correct=answer===item.correct,difficulty=item.difficulty||1,category=item.category||'analysis',expected=(item.estimatedTime||40)*1000,time=response?.responseTimeMs||expected,weight=.65+difficulty*.18,speed=Math.max(.72,Math.min(1.08,expected/Math.max(1000,time))),changePenalty=Math.max(.82,1-(response?.changes||0)*.045),timeoutPenalty=response?.timeout?.75:1,points=correct?weight*speed*changePenalty*timeoutPenalty:0,max=weight;const bucket=categories.get(category)||{points:0,max:0,right:0,total:0,time:0,expected:0,levels:[]};bucket.points+=points;bucket.max+=max;bucket.total++;bucket.time+=time;bucket.expected+=expected;bucket.levels.push(difficulty);if(correct)bucket.right++;categories.set(category,bucket);const section=sections[item.section];section.total++;section.max+=max;section.points+=points;if(correct)section.right++;const skill=skills.get(item.skill)||{points:0,max:0,right:0,total:0};skill.total++;skill.max+=max;skill.points+=points;if(correct)skill.right++;skills.set(item.skill,skill);return{number:index+1,questionId:item.id,section:item.section,question:item.prompt,category,skill:item.skill,difficulty,estimatedTime:item.estimatedTime||40,options:item.options,studentAnswer:answer??null,studentAnswerText:answer===undefined?'Нет ответа':item.options[answer],correctAnswer:item.correct,correctAnswerText:item.options[item.correct],correct,responseTimeMs:time,changes:response?.changes||0,timeout:response?.timeout||false,eeg:response?.eeg||null,explanation:item.explanation||'Ответ определяется условием задания.'}});
  const pct=(right:number,total:number)=>Math.round(right/Math.max(1,total)*100),weighted=(points:number,max:number)=>Math.max(0,Math.min(100,Math.round(points/Math.max(.01,max)*100))),sectionScores=Object.fromEntries(Object.entries(sections).map(([key,value])=>[key,weighted(value.points,value.max)])),skillScores=Object.fromEntries([...skills].map(([key,value])=>[key,weighted(value.points,value.max)]));
  const cognitiveScores=Object.fromEntries([...categories].map(([key,value])=>[key,Math.round(value.points/Math.max(.01,value.max)*100)]));
  const cognitiveLevels=Object.fromEntries([...categories].map(([key,value])=>{const score=value.points/Math.max(.01,value.max)*100,demonstrated=Math.round(value.levels.reduce((a,b)=>a+b,0)/value.levels.length+(score>=78?.7:score<45?-.7:0));return[key,Math.max(1,Math.min(5,demonstrated))]}));
  const totalScore=pct(review.filter(item=>item.correct).length,review.length),sorted=Object.entries(skillScores).sort((a,b)=>a[1]-b[1]),gaps=sorted.filter(([,value])=>value<65).map(([key])=>key),strengths=sorted.filter(([,value])=>value>=80).reverse().map(([key])=>key);
  const averageTime=review.reduce((sum,item)=>sum+item.responseTimeMs,0)/Math.max(1,review.length),accuracy=totalScore,firstHalf=pct(review.slice(0,Math.ceil(review.length/2)).filter(item=>item.correct).length,Math.ceil(review.length/2)),second=review.slice(Math.ceil(review.length/2)),secondHalf=pct(second.filter(item=>item.correct).length,second.length);let behavior=accuracy>=75&&averageTime<35000?'Быстрый и точный':accuracy<65&&averageTime<25000?'Быстрый, но иногда импульсивный':accuracy>=75?'Вдумчивый и точный':'Стратегия решения ещё формируется';if(firstHalf-secondHalf>=18)behavior='К концу диагностики устойчивость внимания снизилась';
  const learning=review.filter(item=>item.category==='learning'),learningFirst=learning[0],learningLast=learning.at(-1),learningScore=pct(learning.filter(item=>item.correct).length,learning.length),learningLabel=learningScore>=80&&Boolean(learningLast?.correct)?'Высокая':learningScore>=50?'Средняя':'Требует дополнительного наблюдения';
  const labels:Record<string,string>={attention:'Внимание',memory:'Память',logic:'Логическое мышление',reaction:'Скорость реакции',processing:'Скорость обработки информации',spatial:'Визуально-пространственное мышление',patterns:'Поиск закономерностей',analysis:'Аналитическое мышление',learning:'Обучаемость',comprehension:'Понимание информации'};
  const best=Object.entries(cognitiveScores).sort((a,b)=>b[1]-a[1])[0],weak=Object.entries(cognitiveScores).sort((a,b)=>a[1]-b[1])[0],aiExplanation=`Ученик ${best?`увереннее проявил навык «${labels[best[0]]}»`:'показал индивидуальный профиль выполнения заданий'}${weak?`, а зона «${labels[weak[0]]}» требует более короткой практики и повторной проверки`:''}. ${firstHalf-secondHalf>=18?'При длительной нагрузке точность постепенно снижалась.':'Темп и точность оставались относительно стабильными.'} Это образовательное описание, а не медицинский вывод.`,readiness=totalScore>=80?'Готов к усложнению':totalScore>=60?'Готов закреплять базу':'Нужна поддержка базы',priority=weak?labels[weak[0]]:'Наблюдение в динамике',nextCheckInDays=totalScore<60?14:28;
  return{sectionScores,skillScores,gaps,strengths,totalScore,recommendations:[`Главный фокус: ${priority}. Начните с 3 коротких тренировок по 8–12 минут без сравнения с другими детьми.`,`Разберите ${gaps.slice(0,2).join(' и ')||'одно задание повышенной сложности'} по схеме: пример с объяснением → похожее задание с подсказкой → самостоятельный перенос правила.`,`Следите за качеством работы, а не только баллом: фиксируйте точность, время, количество исправлений и устойчивость внимания.`,`Проведите контрольный срез через ${nextCheckInDays} дней на новых заданиях той же категории.`],cognitiveScores,cognitiveLevels,decisionSummary:{readiness,priority,nextCheckInDays,strongest:best?labels[best[0]]:null,attentionStability:firstHalf-secondHalf<18},review,processAnalysis:{label:behavior,accuracy,averageResponseMs:Math.round(averageTime),firstHalfAccuracy:firstHalf,secondHalfAccuracy:secondHalf,answerChanges:responses.reduce((sum,item)=>sum+item.changes,0),timeouts:responses.filter(item=>item.timeout).length},learningAnalysis:{label:learningLabel,score:learningScore,firstCorrect:Boolean(learningFirst?.correct),transferCorrect:Boolean(learningLast?.correct),explanation:learningLabel==='Высокая'?'После знакомства с новым правилом ученик быстро начал применять его в новых заданиях.':learningLabel==='Средняя'?'Новое правило усвоено частично; перенос на новую задачу стоит закрепить.':'Для оценки обучаемости нужно повторить блок с другим новым правилом.'},aiExplanation,disclaimer:'Результат описывает выполнение образовательных заданий и не является медицинским диагнозом.'};
}

export function weeklyCheckInQuestions(grade:number,language:'ru'|'kk',weekNumber:number){
  const math=grade<=2?[
    q('cm1','math','Сложение','Сколько будет 26 + 7?',['31','32','33','34'],2),q('cm2','math','Задачи','В коробке было 18 фломастеров, 6 взяли. Сколько осталось?',['10','11','12','13'],2)
  ]:grade<=4?[
    q('cm1','math','Вычисления','Сколько будет 427 − 189?',['228','238','248','318'],1),q('cm2','math','Задачи','В 8 наборах по 6 карточек. Сколько карточек?',['14','42','48','56'],2)
  ]:grade<=7?[
    q('cm1','math','Проценты','25% от 320 равно…',['64','80','90','120'],1),q('cm2','math','Уравнения','Решите: 5x + 4 = 39',['5','6','7','8'],2)
  ]:grade<=9?[
    q('cm1','math','Функции','Для y = 2x + 3 найдите y при x = 5.',['10','11','13','15'],2),q('cm2','math','Геометрия','Гипотенуза при катетах 5 и 12 равна…',['11','12','13','17'],2)
  ]:[
    q('cm1','math','Уравнения','Решите: x² − 16 = 0',['только 4','только −4','−4 и 4','0 и 16'],2),q('cm2','math','Тригонометрия','cos 60° равен…',['0','1/2','√2/2','1'],1)
  ];
  const logic=grade<=4?[
    q('cl1','logic','Последовательности','Продолжите: 5, 10, 15, 20, …',['21','24','25','30'],2),q('cl2','logic','Условия','Мира старше Алии. Кто младше?',['Мира','Алия','они ровесницы','нельзя узнать'],1)
  ]:grade<=7?[
    q('cl1','logic','Закономерности','Продолжите: 3, 8, 15, 24, …',['30','33','35','37'],2),q('cl2','logic','Аналогии','Компас : направление = весы : …',['время','масса','температура','скорость'],1)
  ]:[
    q('cl1','logic','Последовательности','Продолжите: 2, 3, 5, 8, 13, …',['18','20','21','26'],2),q('cl2','logic','Условия','Все B — C. Ни одно C не является D. Может ли B быть D?',['да','нет','только иногда','данных недостаточно'],1)
  ];
  const languageQuestions=language==='kk'?(grade<=4?[
    q('ck1','language','Сөз мағынасы','«Ақылды» сөзіне мағыналас сөзді табыңыз.',['зерек','жалқау','қатты','алыс'],0),q('ck2','language','Сөйлем','«Айша хат жазды» сөйлеміндегі баяндауыш…',['Айша','хат','жазды','Айша хат'],2)
  ]:grade<=7?[
    q('ck1','language','Септік','«Кітапты» сөзі қай септікте?',['атау','барыс','табыс','жатыс'],2),q('ck2','language','Етістік','Келер шақтағы етістікті табыңыз.',['келді','келеді','келіп отыр','келген'],1)
  ]:[
    q('ck1','language','Стиль','Ресми стильге тән белгі…',['бейнелі теңеу','нақты қалыптасқан құрылым','ауызекі сөз','эмоциялық леп'],1),q('ck2','language','Аргументация','Тезисті сенімді ететін не?',['ойды қайталау','тексерілетін дерек','ұзақ тақырып','көп сұрақ'],1)
  ]):(grade<=4?[
    q('cr1','language','Лексика','Синоним слова «аккуратный»…',['неряшливый','опрятный','громкий','медленный'],1),q('cr2','language','Грамматика','Сказуемое: «Ребята решили задачу».',['ребята','решили','задачу','решили задачу'],1)
  ]:grade<=7?[
    q('cr1','language','Орфография','Выберите правильное написание.',['в течении дня','в течение дня','в теченье дня','в-течение дня'],1),q('cr2','language','Причастие','Найдите причастие.',['решённый','решать','решил','решение'],0)
  ]:[
    q('cr1','language','Стиль','Признак публицистического стиля…',['только термины','общественно значимая тема и оценка','бытовой диалог','инструкция прибора'],1),q('cr2','language','Аргументация','Какой аргумент сильнее?',['личное предположение','проверяемый факт с источником','повтор тезиса','риторический вопрос'],1)
  ]);
  return [...math,...logic,...languageQuestions].map((item,index)=>({...item,id:`check-${Math.max(1,weekNumber)}-${index}-${item.id}`}));
}

export function scoreWeeklyCheckIn(grade:number,language:'ru'|'kk',weekNumber:number,answers:Record<string,number>){
  const questions=weeklyCheckInQuestions(grade,language,weekNumber),sections:Record<string,{right:number;total:number}>={math:{right:0,total:0},logic:{right:0,total:0},language:{right:0,total:0}},skills=new Map<string,{right:number;total:number}>();
  for(const item of questions){const correct=answers[item.id]===item.correct;sections[item.section].total++;if(correct)sections[item.section].right++;const skill=skills.get(item.skill)||{right:0,total:0};skill.total++;if(correct)skill.right++;skills.set(item.skill,skill)}
  const percent=(right:number,total:number)=>Math.round(right/Math.max(1,total)*100),sectionScores=Object.fromEntries(Object.entries(sections).map(([key,value])=>[key,percent(value.right,value.total)])),skillScores=Object.fromEntries([...skills].map(([key,value])=>[key,percent(value.right,value.total)])),sorted=Object.entries(skillScores).sort((a,b)=>a[1]-b[1]),gaps=sorted.filter(([,value])=>value<70).map(([key])=>key),strengths=sorted.filter(([,value])=>value>=80).reverse().map(([key])=>key),totalScore=percent(Object.values(sections).reduce((sum,item)=>sum+item.right,0),questions.length);
  return{sectionScores,skillScores,gaps,strengths,totalScore};
}
