import { resolveSkillProfiles } from './curriculum.js';

type GeneratedTask={dayIndex:number;orderIndex:number;subject:string;skill:string;grade:number;difficulty:number;prompt:string;options:string[];correctOption:number;hint:string;explanation:string;xpReward:number};
const optionSet=(correct:number,seed:number)=>{const unique=new Set<number>([correct]);const offsets=[1+seed%4,-(1+(seed+1)%4),2+(seed+3)%7,5+(seed%6),-(5+seed%5),10+seed%9];for(const offset of offsets){const candidate=correct+offset;if(candidate>=0)unique.add(candidate);if(unique.size===4)break}let fallback=1;while(unique.size<4){unique.add(correct+fallback++*3)}const values=[...unique].slice(0,4),shift=seed%4,options=[...values.slice(shift),...values.slice(0,shift)];return{options:options.map(String),correctOption:options.indexOf(correct)}};
const numeric=(day:number,order:number,grade:number,skill:string):GeneratedTask=>{const seed=day*11+order*5+grade;if(grade<=2){const a=8+seed%24,b=3+(seed*3)%12,subtract=seed%2===0,answer=subtract?a-b:a+b,set=optionSet(answer,seed);return{dayIndex:day,orderIndex:order,subject:'Математика',skill:'Вычисления',grade,difficulty:1,prompt:`Сколько будет ${a} ${subtract?'−':'+'} ${b}?`,...set,hint:subtract?'Отсчитай назад по частям.':'Сначала прибавь десятки, затем единицы.',explanation:`${a} ${subtract?'−':'+'} ${b} = ${answer}.`,xpReward:10}}if(grade<=4){const a=3+seed%7,b=2+(seed*2)%8,answer=a*b,set=optionSet(answer,seed);return{dayIndex:day,orderIndex:order,subject:'Математика',skill:seed%3===0?'Задачи':'Умножение',grade,difficulty:2,prompt:seed%3===0?`В ${a} коробках по ${b} карандашей. Сколько карандашей всего?`:`Чему равно ${a} × ${b}?`,...set,hint:'Одинаковые группы можно сложить или умножить.',explanation:`${a} групп по ${b}: ${a} × ${b} = ${answer}.`,xpReward:12}}if(grade<=7){const x=2+seed%9,k=2+seed%4,c=1+seed%7,total=k*x+c,set=optionSet(x,seed);return{dayIndex:day,orderIndex:order,subject:'Математика',skill:skill||'Уравнения',grade,difficulty:2,prompt:`Решите уравнение: ${k}x + ${c} = ${total}`,...set,hint:`Сначала вычти ${c}, затем раздели на ${k}.`,explanation:`${k}x = ${total-c}, поэтому x = ${x}.`,xpReward:14}}const x=2+seed%7,answer=x*x,set=optionSet(answer,seed);return{dayIndex:day,orderIndex:order,subject:'Математика',skill:skill||'Алгебра',grade,difficulty:3,prompt:`Найдите значение x², если x = ${x}.`,...set,hint:'Умножь число само на себя.',explanation:`${x}² = ${x} × ${x} = ${answer}.`,xpReward:16}};
const advancedNumeric=(day:number,order:number,grade:number,skill:string):GeneratedTask=>{const seed=day*13+order*7+grade,kind=seed%4,common={dayIndex:day,orderIndex:order,subject:'Математика',grade,difficulty:3,xpReward:16};if(kind===0){const x=2+seed%6,k=2+seed%4,c=seed%5,answer=k*x+c,set=optionSet(answer,seed);return{...common,skill:skill||'Функции',prompt:`Если f(x) = ${k}x + ${c}, найдите f(${x}).`,...set,hint:'Подставь указанное значение вместо x.',explanation:`f(${x}) = ${k} × ${x} + ${c} = ${answer}.`}}if(kind===1){const base=200+seed%8*100,percent=[10,20,25,50][seed%4],answer=base*percent/100,set=optionSet(answer,seed);return{...common,skill:skill||'Проценты',prompt:`Найдите ${percent}% от ${base}.`,...set,hint:`Раздели ${base} на 100 и умножь на ${percent}.`,explanation:`${base} × ${percent}/100 = ${answer}.`}}if(kind===2){const root=3+seed%9,answer=root,set=optionSet(answer,seed);return{...common,skill:skill||'Квадратные корни',prompt:`Вычислите √${root*root}.`,...set,hint:'Какое положительное число при умножении на себя даёт подкоренное?',explanation:`${root} × ${root} = ${root*root}, поэтому ответ ${root}.`}}const x=2+seed%7,answer=x*x,set=optionSet(answer,seed);return{...common,skill:skill||'Степени',prompt:`Найдите значение x², если x = ${x}.`,...set,hint:'Умножь число само на себя.',explanation:`${x}² = ${x} × ${x} = ${answer}.`}};
const logic=(day:number,order:number,grade:number):GeneratedTask=>{const seed=day*7+order+grade;if(seed%2===0){const start=1+seed%5,step=grade<=4?2:grade<=7?3:5,answer=start+step*4,set=optionSet(answer,seed);return{dayIndex:day,orderIndex:order,subject:'Логика',skill:'Последовательности',grade,difficulty:Math.ceil(grade/4),prompt:`Продолжите ряд: ${start}, ${start+step}, ${start+step*2}, ${start+step*3}, …`,...set,hint:'Найди одинаковое изменение между соседними числами.',explanation:`Каждый раз прибавляем ${step}, поэтому следующее число — ${answer}.`,xpReward:12}}return{dayIndex:day,orderIndex:order,subject:'Логика',skill:'Аналогии',grade,difficulty:Math.ceil(grade/4),prompt:'Книга относится к чтению, как музыка относится к…',options:['рисованию','слушанию','счёту','письму'],correctOption:1,hint:'Подумай, какое действие выполняют с каждым объектом.',explanation:'Книгу читают, а музыку слушают.',xpReward:12}};
const languageTask=(day:number,order:number,grade:number,language:'ru'|'kk'):GeneratedTask=>{const common={dayIndex:day,orderIndex:order,subject:language==='kk'?'Қазақ тілі':'Русский язык',grade,difficulty:Math.ceil(grade/4),xpReward:12};if(language==='kk'){const items=[{skill:'Сөз мағынасы',prompt:'«Қуанышты» сөзіне мағыналас сөзді таңдаңыз.',options:['мұңды','көңілді','ашулы','әлсіз'],correctOption:1,hint:'Мағынасы жақын сөзді іздеңіз.',explanation:'«Қуанышты» және «көңілді» — мағыналас сөздер.'},{skill:'Емле',prompt:'Дұрыс жазылған сөзді табыңыз.',options:['оқұшы','оқушы','оқышы','оқушыы'],correctOption:1,hint:'Сөздің түбірі — «оқу».',explanation:'Дұрыс нұсқа — «оқушы».'},{skill:'Сөйлем',prompt:'«Бала есеп шығарды» сөйлеміндегі бастауышты табыңыз.',options:['бала','есеп','шығарды','есеп шығарды'],correctOption:0,hint:'Іс-әрекетті кім орындады?',explanation:'Есепті шығарған — бала, сондықтан бастауыш «бала».'}];return{...common,...items[(day+order)%items.length]}}const items=[{skill:'Лексика',prompt:'Выберите синоним слова «внимательный».',options:['рассеянный','сосредоточенный','быстрый','громкий'],correctOption:1,hint:'Ищи слово с близким значением.',explanation:'«Сосредоточенный» близок по значению к слову «внимательный».'},{skill:'Орфография',prompt:'В каком слове нет ошибки?',options:['задачя','задача','зода́ча','задачча'],correctOption:1,hint:'После Ч обычно пишется А, не Я.',explanation:'Правильное написание — «задача».'},{skill:'Понимание текста',prompt:'«После урока Айдана проверила решение». Что она сделала после урока?',options:['начала урок','проверила решение','ушла спать','прочитала правило'],correctOption:1,hint:'Ответ прямо указан в предложении.',explanation:'После урока Айдана проверила решение.'}];return{...common,...items[(day+order)%items.length]}};

const cognitiveTask=(day:number,order:number,grade:number,language:'ru'|'kk'):GeneratedTask=>{
  const kk=language==='kk',difficulty=day<2?1:day<5?2:3,common={dayIndex:day,orderIndex:order,subject:kk?'Ми жаттығуы':'Нейроразминка',grade,difficulty,xpReward:14+difficulty*2};
  const tasks=[
    {skill:kk?'Таңдамалы зейін':'Избирательное внимание',prompt:kk?'Нысанды ғана сана: ○ △ ○ □ ○ △ ○. Мұнда неше ○ бар?':'Считай только цель: ○ △ ○ □ ○ △ ○. Сколько здесь ○?',options:['3','4','5','6'],correctOption:1,hint:kk?'Бір таңбаны таңда да, қатарды баяу тексер.':'Выбери один символ-цель и медленно проверь ряд.',explanation:kk?'○ таңбасы төрт рет кездеседі. Бұл тапсырма кедергілер арасынан нысанды табуды жаттықтырады.':'Символ ○ встречается четыре раза. Задание тренирует поиск цели среди помех.'},
    {skill:kk?'Жұмыс жады':'Рабочая память',prompt:kk?'Қатарды кері ретпен таңда: 3 – 8 – 1 – 6':'Выбери последовательность в обратном порядке: 3 – 8 – 1 – 6',options:['6 – 1 – 8 – 3','6 – 8 – 1 – 3','3 – 8 – 1 – 6','1 – 6 – 8 – 3'],correctOption:0,hint:kk?'Соңғы саннан баста.':'Начни с последнего числа.',explanation:kk?'Кері рет: 6 – 1 – 8 – 3. Бұл ақпаратты қысқа уақыт есте ұстап, өңдеуді жаттықтырады.':'Обратный порядок: 6 – 1 – 8 – 3. Это упражнение на удержание и обработку информации.'},
    {skill:kk?'Импульсті тежеу':'Контроль импульса',prompt:kk?'Ереже: көрсетілген бағыттың ҚАРАМА-ҚАРСЫСЫН таңда. Бағыт: →':'Правило: выбери направление, ПРОТИВОПОЛОЖНОЕ показанному. Направление: →',options:['→','←','↑','↓'],correctOption:1,hint:kk?'Алдымен автоматты жауапты тоқтат, содан кейін қарама-қарсысын таңда.':'Останови первый автоматический ответ и выбери противоположный.',explanation:kk?'→ бағытына қарама-қарсы — ←. Тапсырма асығыс жауапты тоқтатуды жаттықтырады.':'Противоположное направлению → — это ←. Задание тренирует остановку поспешного ответа.'},
    {skill:kk?'Ережені ауыстыру':'Переключение правила',prompt:kk?'Ереже: жұп санға +2, тақ санға −1. 7 саны үшін жауапты таңда.':'Правило: к чётному числу прибавь 2, от нечётного вычти 1. Выбери ответ для числа 7.',options:['5','6','8','9'],correctOption:1,hint:kk?'Алдымен санның жұп не тақ екенін анықта.':'Сначала определи, чётное число или нечётное.',explanation:kk?'7 — тақ сан, сондықтан 7 − 1 = 6. Бұл тапсырма ережелер арасында ауысуды жаттықтырады.':'7 — нечётное число, поэтому 7 − 1 = 6. Задание тренирует применение и переключение правил.'},
    {skill:kk?'Жадты жаңарту':'Обновление памяти',prompt:kk?'8-ден баста. +2, кейін −3, кейін +4. Соңғы сан қандай?':'Начни с 8. Прибавь 2, затем вычти 3, затем прибавь 4. Какое число получилось?',options:['9','10','11','12'],correctOption:2,hint:kk?'Әр қадамнан кейін аралық нәтижені есте сақта.':'Удерживай промежуточный результат после каждого шага.',explanation:kk?'8 + 2 = 10; 10 − 3 = 7; 7 + 4 = 11. Бұл жұмыс жадындағы ақпаратты жаңартуды жаттықтырады.':'8 + 2 = 10; 10 − 3 = 7; 7 + 4 = 11. Это тренирует обновление информации в рабочей памяти.'},
    {skill:kk?'Тұрақты зейін':'Устойчивое внимание',prompt:kk?'Үлгіні тап: 4837. Қай нұсқа дәл сәйкес келеді?':'Найди точное совпадение с образцом: 4837. Какой вариант полностью совпадает?',options:['4873','4837','4387','4831'],correctOption:1,hint:kk?'Әр орынды солдан оңға қарай салыстыр.':'Сравни каждую позицию слева направо.',explanation:kk?'Тек 4837 үлгіге толық сәйкес келеді. Тапсырма дәлдікті уақыт бойы сақтауды жаттықтырады.':'Только 4837 полностью совпадает с образцом. Задание тренирует устойчивое внимание к деталям.'},
    {skill:kk?'Когнитивті икемділік':'Когнитивная гибкость',prompt:kk?'Жаңа ереже: саннан кейін әріп, әріптен кейін сан келуі керек. Дұрыс қатарды таңда.':'Новое правило: после числа должна идти буква, после буквы — число. Выбери правильный ряд.',options:['2 – А – 5 – Б','2 – 5 – А – Б','А – Б – 2 – 5','2 – А – Б – 5'],correctOption:0,hint:kk?'Сан мен әріп кезектесуі керек.':'Числа и буквы должны чередоваться.',explanation:kk?'2 – А – 5 – Б қатарында сан мен әріп кезектеседі. Бұл жаңа ережеге тез ауысуды жаттықтырады.':'В ряду 2 – А – 5 – Б числа и буквы чередуются. Это упражнение на гибкое переключение правила.'}
  ];
  return{...common,...tasks[day%tasks.length]};
};

const grade3Task=(day:number,order:number,skillId:string,language:'ru'|'kk'):GeneratedTask=>{
  const seed=day*19+order*7+3,difficulty=day===0?1:day>=4?3:2,common={dayIndex:day,orderIndex:order,grade:3,difficulty,xpReward:10+difficulty*2};
  if(skillId==='math-calculation'){const a=120+(seed*13)%380,b=30+(seed*17)%190,subtract=(day+order)%2===1,answer=subtract?a-b:a+b,set=optionSet(answer,seed);return{...common,subject:'Математика',skill:'Вычисления',prompt:`${a} ${subtract?'−':'+'} ${b} = ?`,...set,hint:subtract?'Вычитай сотни, десятки и единицы по частям.':'Сложи сотни, затем десятки и единицы.',explanation:`Верный результат: ${a} ${subtract?'−':'+'} ${b} = ${answer}. Проверь обратным действием.`}}
  if(skillId==='math-multiplication'){const groups=3+seed%7,items=2+(seed*3)%8,answer=groups*items,set=optionSet(answer,seed);return{...common,subject:'Математика',skill:'Умножение',prompt:order%2===0?`В ${groups} одинаковых наборах по ${items} деталей. Сколько деталей всего?`:`Чему равно ${groups} × ${items}?`,...set,hint:'Представь одинаковые группы и замени сложение умножением.',explanation:`${groups} групп по ${items}: ${groups} × ${items} = ${answer}.`}}
  if(skillId==='math-division'){const divisor=2+seed%7,answer=2+(seed*2)%8,total=divisor*answer,set=optionSet(answer,seed);return{...common,subject:'Математика',skill:'Деление',prompt:`${total} деталей разделили поровну на ${divisor} команд. Сколько получила каждая?`,...set,hint:`Найди число, которое при умножении на ${divisor} даёт ${total}.`,explanation:`${total} ÷ ${divisor} = ${answer}. Проверка: ${answer} × ${divisor} = ${total}.`}}
  if(skillId==='math-word-problem'){const boxes=3+seed%5,each=4+(seed*2)%7,extra=2+seed%6,answer=boxes*each-extra,set=optionSet(answer,seed);return{...common,subject:'Математика',skill:'Понимание задачи',prompt:`В ${boxes} коробках по ${each} фломастеров. ${extra} фломастера использовали. Сколько осталось?`,...set,hint:'Шаг 1: найди общее количество. Шаг 2: вычти использованные.',explanation:`План: ${boxes} × ${each} = ${boxes*each}; затем ${boxes*each} − ${extra} = ${answer}.`}}
  if(skillId==='math-geometry'){const a=3+seed%8,b=2+(seed*2)%6,answer=2*(a+b),set=optionSet(answer,seed);return{...common,subject:'Математика',skill:'Геометрия',prompt:`Прямоугольник: длина ${a} см, ширина ${b} см. Найди периметр.`,...set,hint:'Периметр — сумма длин всех четырёх сторон.',explanation:`P = (${a} + ${b}) × 2 = ${answer} см.`}}
  if(skillId==='logic-classification'){return{...common,subject:'Логика',skill:'Классификация',prompt:'Какой объект лишний по главному признаку?',options:['квадрат','треугольник','прямоугольник','яблоко'],correctOption:3,hint:'Сравни, к какой группе относится каждый объект.',explanation:'Первые три — геометрические фигуры, яблоко относится к другой группе.'}}
  if(skillId==='logic-analogy'){return{...common,subject:'Логика',skill:'Аналогии',prompt:'Линейка относится к длине, как часы относятся к…',options:['массе','времени','цвету','температуре'],correctOption:1,hint:'Каждый прибор что-то измеряет.',explanation:'Линейкой измеряют длину, часами — время.'}}
  if(skillId==='language-comprehension'){const kk=language==='kk';return{...common,subject:kk?'Қазақ тілі':'Русский язык',skill:kk?'Мәтінді түсіну':'Понимание текста',prompt:kk?'«Айша есепті екі рет тексеріп, қатесін түзетті». Айша не үшін есепті қайта қарады?':'«Алина дважды проверила решение и исправила ошибку». Зачем она вернулась к решению?',options:kk?['жаңа есеп бастау үшін','қатені табу үшін','кітап оқу үшін','уақытты білу үшін']:['чтобы начать новую задачу','чтобы найти ошибку','чтобы прочитать книгу','чтобы узнать время'],correctOption:1,hint:kk?'Сөйлемдегі әрекеттің нәтижесіне назар аудар.':'Посмотри, что произошло после проверки.',explanation:kk?'Тексеру Айшаға қатені тауып, түзетуге көмектесті.':'Проверка помогла Алине найти и исправить ошибку.'}}
  if(skillId==='language-spelling'){return languageTask(day,order,3,language)}
  if(skillId==='language-word-meaning'||skillId==='language-sentence'||skillId==='language-vocabulary')return languageTask(day,order,3,language);
  return logic(day,order,3);
};

const grade3Plan=(language:'ru'|'kk',gaps:string[],sectionScores:Record<string,number>)=>{
  const focus=resolveSkillProfiles(gaps,sectionScores,language),tasks:GeneratedTask[]=[];
  for(let day=0;day<7;day++)for(let order=0;order<4;order++){
    const profile=order<2?focus[0]:order===2?focus[1]:(day%2===0?focus[0]:focus[focus.length-1]);
    tasks.push(grade3Task(day,order,profile.id,language));
  }
  for(let day=0;day<7;day++)tasks.push(cognitiveTask(day,4,3,language));
  return tasks;
};

export function generateHomeworkTasks(grade:number,language:'ru'|'kk',gaps:string[],sectionScores:Record<string,number>){
  if(grade===3)return grade3Plan(language,gaps,sectionScores);
  const weakest=Object.entries(sectionScores).sort((a,b)=>a[1]-b[1])[0]?.[0]||'math',tasks:GeneratedTask[]=[],perDay=grade<=2?3:grade<=8?4:5;
  for(let day=0;day<7;day++)for(let order=0;order<perDay;order++){const emphasis=order<2?weakest:(day+order)%3===0?'logic':(day+order)%2===0?'language':'math',mathSkill=gaps.find(item=>/вычис|дроб|урав|алгеб|геометр|процент|задач|функц|корн|степ/i.test(item))||'';const task=emphasis==='math'?(grade>=8?advancedNumeric(day,order,grade,mathSkill):numeric(day,order,grade,mathSkill)):emphasis==='logic'?logic(day,order,grade):languageTask(day,order,grade,language);task.difficulty=Math.max(1,Math.min(3,task.difficulty+(day>=4?1:day===0?-1:0)));task.xpReward+=day>=4?3:0;tasks.push(task)}
  for(let day=0;day<7;day++)tasks.push(cognitiveTask(day,perDay,grade,language));
  return tasks;
}
