import {useEffect,useMemo,useState} from 'react';
import {ArrowRight,Brain,Check,Compass,GraduationCap,Lightbulb,Sparkles,Target} from 'lucide-react';
import {api} from './api';
import './career-guidance.css';
import './career-teacher.css';

const questions=[
['Мне нравится разбираться, почему система работает именно так.','research'],['Я люблю создавать изображения, истории или необычные идеи.','creative'],['Мне интересно помогать людям и объяснять сложное понятным языком.','social'],['Мне нравится собирать устройства, программировать или конструировать.','technical'],['Я легко организую команду и распределяю задачи.','leadership'],['Мне комфортно работать с числами, таблицами и закономерностями.','analytical'],['Я хочу проводить эксперименты и проверять гипотезы.','research'],['Мне нравится придумывать дизайн продукта или интерфейса.','creative'],['Я получаю удовольствие, когда кому-то становится понятнее после моего объяснения.','social'],['Я предпочитаю сделать работающий прототип, а не только обсуждать идею.','technical'],['Мне интересно презентовать проект и убеждать аудиторию.','leadership'],['Я замечаю ошибки и несоответствия в информации.','analytical']];
const labels:any={research:'Исследования и наука',creative:'Дизайн и креативные индустрии',social:'Образование и работа с людьми',technical:'Инженерия и технологии',leadership:'Предпринимательство и управление',analytical:'Аналитика и данные'};

export default function CareerGuidancePage(){
 const [data,setData]=useState<any>(null),[answers,setAnswers]=useState<number[]>(Array(questions.length).fill(0)),[step,setStep]=useState(0),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[query,setQuery]=useState(''),[selected,setSelected]=useState<any>(null),[review,setReview]=useState({status:'CONFIRMED',note:''});
 useEffect(()=>{api<any>('/career-profile').then(r=>{setData(r);if(r.profile?.responses)setAnswers(r.profile.responses)}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
 const completed=answers.filter(Boolean).length,canSubmit=completed===questions.length,result=data?.profile;
 const current=questions[step],options=[['Совсем не про меня',1],['Скорее нет',2],['Скорее да',3],['Очень похоже на меня',4]] as const;
 const submit=async()=>{setSaving(true);setError('');try{const r=await api<any>('/career-profile',{method:'POST',body:JSON.stringify({responses:answers})});setData(r)}catch(e){setError(e instanceof Error?e.message:'Не удалось сохранить профиль')}finally{setSaving(false)}};
 const saveReview=async()=>{if(!selected||review.note.trim().length<3)return;setSaving(true);try{const r=await api<any>(`/career-profile/${selected.id}/review`,{method:'POST',body:JSON.stringify(review)});const profiles=data.profiles.map((item:any)=>item.id===selected.id?{...item,review:r.review}:item);setData({...data,profiles});setSelected({...selected,review:r.review})}catch(e){setError(e instanceof Error?e.message:'Не удалось сохранить решение')}finally{setSaving(false)}};
 if(loading)return <div className="loading-panel"><span className="loader dark-loader"/>Готовим профориентацию…</div>;
 if(data?.mode==='teacher'){const visible=data.profiles.filter((item:any)=>`${item.name} ${item.className} ${item.publicId}`.toLowerCase().includes(query.toLowerCase()));return <div className="career-page"><div className="page-head"><div><span>КАРЬЕРНЫЕ ГИПОТЕЗЫ УЧЕНИКОВ</span><h1>Профориентация класса</h1><p>Просматривайте результаты, обсуждайте направления и фиксируйте педагогическое наблюдение.</p></div></div>{error&&<div className="api-error">{error}</div>}<div className="career-teacher-kpis"><span><b>{data.profiles.filter((x:any)=>x.eligible).length}</b><small>доступно с 7 класса</small></span><span><b>{data.profiles.filter((x:any)=>x.profile).length}</b><small>профилей готово</small></span><span><b>{data.profiles.filter((x:any)=>x.review).length}</b><small>обсуждено педагогом</small></span></div><label className="career-search"><Compass/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ученик, класс или IUI ID…"/></label><div className="career-roster">{visible.map((item:any)=><button key={item.id} disabled={!item.eligible||!item.profile} onClick={()=>{setSelected(item);setReview({status:item.review?.status||'CONFIRMED',note:item.review?.note||''})}}><span><b>{item.name}</b><small>{item.className} · {item.publicId}</small></span>{!item.eligible?<em>Откроется с 7 класса</em>:item.profile?<><strong>{labels[item.profile.topDirections[0]?.key]||'Профиль готов'}</strong><i className={item.review?'reviewed':''}>{item.review?'Обсуждено':'Открыть'}</i></>:<em>Не пройдено</em>}</button>)}</div>{selected&&<div className="career-review-backdrop" onMouseDown={()=>setSelected(null)}><section onMouseDown={e=>e.stopPropagation()}><header><div><small>ПЕДАГОГИЧЕСКОЕ ОБСУЖДЕНИЕ</small><h2>{selected.name}</h2><p>{selected.className} · результат ребёнка не изменяется</p></div><button onClick={()=>setSelected(null)}>×</button></header><div className="career-review-directions">{selected.profile.topDirections.map((x:any)=><span key={x.key}><b>{labels[x.key]}</b><small>{x.score}% совпадения</small></span>)}</div><label>Статус<select value={review.status} onChange={e=>setReview({...review,status:e.target.value})}><option value="CONFIRMED">Можно проверить на практике</option><option value="NEEDS_DISCUSSION">Нужно обсудить с семьёй</option><option value="OBSERVATION">Продолжить наблюдение</option></select></label><label>Наблюдение преподавателя<textarea value={review.note} onChange={e=>setReview({...review,note:e.target.value})} placeholder="Что вы замечаете на занятиях? Какие проекты стоит попробовать?"/></label><button className="primary" disabled={saving||review.note.trim().length<3} onClick={saveReview}>{saving?'Сохраняем…':'Сохранить наблюдение'}<Check/></button></section></div>}</div>}
 if(data?.eligible===false)return <div className="career-locked"><Compass/><span>ПРОФОРИЕНТАЦИЯ IUI</span><h1>Сферы интереса — сейчас,<br/>карьерный профиль — с 7 класса</h1><p>До 7 класса IUI развивает широкий набор навыков без раннего выбора профессии. Полная профориентация откроется позже.</p></div>;
 return <div className="career-page"><div className="page-head"><div><span>ПРОФОРИЕНТАЦИЯ · 7–11 КЛАСС</span><h1>Карта направлений</h1><p>Интересы, учебные результаты и когнитивный профиль объединяются в несколько возможных траекторий.</p></div></div>{error&&<div className="api-error">{error}</div>}
 {result?<><section className="career-hero"><Compass/><div><small>ВАШ ПРОФИЛЬ СФОРМИРОВАН</small><h2>{result.topDirections.slice(0,2).map((x:any)=>labels[x.key]).join(' · ')}</h2><p>Это ориентир для проб и развития навыков, а не окончательный выбор профессии.</p></div><button onClick={()=>setData({...data,profile:null})}>Пройти заново</button></section><div className="career-directions">{result.topDirections.map((item:any,index:number)=><article key={item.key}><i>{index+1}</i><span><small>{index===0?'ВЕДУЩЕЕ НАПРАВЛЕНИЕ':'ДОПОЛНИТЕЛЬНАЯ ТРАЕКТОРИЯ'}</small><h3>{labels[item.key]}</h3><p>{item.reason}</p><em><b style={{width:`${item.score}%`}}/></em><strong>{item.score}% совпадения</strong></span></article>)}</div><section className="career-next"><Target/><div><small>ПЛАН ПРОВЕРКИ ГИПОТЕЗЫ</small><h2>Не выбирать — попробовать</h2><ol>{result.nextSteps.map((x:string)=><li key={x}><Check/>{x}</li>)}</ol></div></section><section className="career-note"><Lightbulb/><p>EEG используется только как дополнительное наблюдение за работой во время учебных задач. IUI не определяет профессию по активности мозга и не ограничивает выбор ребёнка.</p></section></>:<section className="career-test"><header><div><Brain/><span><small>ИНТЕРЕСЫ И ПРЕДПОЧТЕНИЯ</small><b>Утверждение {step+1} из {questions.length}</b></span></div><strong>{Math.round(completed/questions.length*100)}%</strong></header><i><b style={{width:`${completed/questions.length*100}%`}}/></i><main><Sparkles/><h2>{current[0]}</h2><div>{options.map(([label,value])=><button className={answers[step]===value?'active':''} onClick={()=>{const next=[...answers];next[step]=value;setAnswers(next)}} key={value}><span>{label}</span>{answers[step]===value&&<Check/>}</button>)}</div></main><footer><button disabled={step===0} onClick={()=>setStep(x=>x-1)}>Назад</button>{step<questions.length-1?<button className="primary" disabled={!answers[step]} onClick={()=>setStep(x=>x+1)}>Далее<ArrowRight/></button>:<button className="primary" disabled={!canSubmit||saving} onClick={submit}>{saving?'Анализируем…':'Сформировать профиль'}<GraduationCap/></button>}</footer></section>}</div>;
}
