import { useEffect, useMemo, useRef, useState } from 'react';
import { Activity, ArrowLeft, ArrowRight, Bluetooth, Brain, Check, Clock3, FileText, Gauge, GraduationCap, Languages, Lightbulb, Printer, RefreshCw, Sparkles, Target, Wifi, X } from 'lucide-react';
import { api, authApi, type EegSample } from './api';
import { bluetoothManager } from './bluetoothManager';
import CreativeTaskInteraction, { isCreativeTask } from './CreativeTaskInteraction';
import './diagnostic-page.css';
import './diagnostic-neuro.css';
import './diagnostic-sections.css';
import './diagnostic-cognitive.css';
import './diagnostic-decision.css';
import './diagnostic-puzzle.css';
import './signal-warning.css';
import './creative-task-interaction.css';

type Section='math'|'logic'|'language';
type Question={id:string;section:Section;skill:string;prompt:string;options:string[];difficulty:number;category:string;recommendedAgeRange:[number,number];estimatedTime:number};
const sectionInfo:Record<Section,{title:string;minutes:number;icon:any}>={math:{title:'Когнитивная математика',minutes:15,icon:GraduationCap},logic:{title:'Логика и внимание',minutes:15,icon:Brain},language:{title:'Понимание информации',minutes:15,icon:Languages}};
const sectionOrder:Section[]=['math','logic','language'];

function SectionNeuro({attempt}:{attempt:any}){const timeline=Array.isArray(attempt.sectionTimeline)?attempt.sectionTimeline.filter((item:any)=>item.metrics):[];if(!timeline.length)return null;const names:Record<string,string>={math:'Математика',logic:'Логика',language:attempt.language==='kk'?'Қазақ тілі':'Русский язык'};const weakest=[...timeline].sort((a,b)=>(a.metrics.focus||0)-(b.metrics.focus||0))[0];return <section className="section-neuro"><header><Brain/><div><small>EEG ПО УЧЕБНЫМ БЛОКАМ</small><h2>Где нагрузка ощущалась сильнее</h2></div></header><div>{timeline.map((item:any,index:number)=><article key={item.section}><span><i>{index+1}</i><b>{names[item.section]||item.section}</b></span><div><em><small>Внимание</small><strong>{item.metrics.attention}%</strong></em><em><small>Фокус</small><strong>{item.metrics.focus}%</strong></em><em><small>Вовлечённость</small><strong>{item.metrics.engagement}%</strong></em></div><i className="section-focus"><em style={{width:`${item.metrics.focus}%`}}/></i></article>)}</div>{weakest&&<footer><Lightbulb/><p>На блоке «{names[weakest.section]}» фокус был ниже остальных. Начинайте работу с коротких знакомых заданий и повышайте сложность постепенно.</p></footer>}</section>}

function Result({attempt}:{attempt:any}){
  const sections=[['Математика',attempt.sectionScores.math],['Логика',attempt.sectionScores.logic],[attempt.language==='kk'?'Қазақ тілі':'Русский язык',attempt.sectionScores.language]];const eeg=attempt.eegSession,details=attempt.answers&&typeof attempt.answers==='object'&&!Array.isArray(attempt.answers)?attempt.answers:{},cognitive=details.cognitiveScores||{},levels=details.cognitiveLevels||{},review=Array.isArray(details.review)?details.review:[],categoryEeg=Array.isArray(details.categoryEeg)?details.categoryEeg:[],cognitiveNames:Record<string,string>={attention:'Внимание',memory:'Память',logic:'Логическое мышление',reaction:'Скорость реакции',processing:'Скорость обработки',spatial:'Визуально-пространственное мышление',patterns:'Поиск закономерностей',analysis:'Аналитическое мышление',learning:'Обучаемость',comprehension:'Понимание информации'};
  return <div className="diagnostic-result">
    <section className="diagnostic-score"><div><Sparkles/><span>БЕСПЛАТНАЯ ДИАГНОСТИКА ЗАВЕРШЕНА</span></div><strong>{attempt.totalScore}<small>%</small></strong><h2>{attempt.totalScore>=85?'Уверенное владение программой':attempt.totalScore>=65?'Хорошая база с отдельными пробелами':attempt.totalScore>=45?'База сформирована частично':'Нужна системная поддержка'}</h2><p>Объединённый образовательный срез знаний и нейроактивности.</p><button onClick={()=>window.print()}><Printer/>Сохранить полный отчёт в PDF</button></section>
    <div className="diagnostic-section-scores">{sections.map(([name,value]:any)=><article key={name}><span>{name}<b>{value}%</b></span><i><em style={{width:`${value}%`}}/></i><small>{value>=80?'Сильная зона':value>=60?'Нужно закрепление':'Приоритетная зона'}</small></article>)}</div>
    {eeg&&<section className="diagnostic-neuro"><header><Activity/><div><small>EEG ВО ВРЕМЯ РЕШЕНИЯ</small><h2>Как мозг справлялся с нагрузкой</h2></div><span><Wifi/>Сигнал {Math.round(eeg.signalAvg||0)}%</span></header><div>{[['Внимание',eeg.attentionAvg],['Медитация',eeg.meditationAvg],['Вовлечённость',eeg.engagementAvg],['Фокус',eeg.focusAvg],['Расслабление',eeg.relaxationAvg],['Усталость',eeg.fatigueScore]].map(([name,value]:any)=><article key={name}><b>{Math.round(value||0)}%</b><small>{name}</small><i><em style={{width:`${Math.round(value||0)}%`}}/></i></article>)}</div><p><Brain/><span><b>{eeg.emotionalState||'Состояние определено'}</b><small>{eeg.aiSummary} {eeg.aiRecommendations}</small></span></p></section>}
    <SectionNeuro attempt={attempt}/>
    {details.aiExplanation&&<section className="cognitive-explanation"><Sparkles/><div><small>AI-ОБЪЯСНЕНИЕ</small><h2>Как ученик решал задания</h2><p>{details.aiExplanation}</p><em>{details.disclaimer}</em></div></section>}
    {details.decisionSummary&&<section className="decision-summary"><header><Target/><div><small>ЧТО ДЕЛАТЬ ДАЛЬШЕ</small><h2>{details.decisionSummary.readiness}</h2></div></header><div><span><small>Главный приоритет</small><b>{details.decisionSummary.priority}</b></span><span><small>Повторный срез</small><b>через {details.decisionSummary.nextCheckInDays} дней</b></span><span><small>Устойчивость внимания</small><b>{details.decisionSummary.attentionStability?"стабильная":"снижается при нагрузке"}</b></span></div></section>}{Object.keys(cognitive).length>0&&<section className="cognitive-results"><header><Brain/><div><small>COGNITIVE LEVEL ANALYSIS</small><h2>Когнитивный профиль</h2><p>Уровень определяется по точности, сложности и времени ответа, а класс используется только как начальная точка.</p></div></header><div>{Object.entries(cognitive).map(([key,value]:any)=><article key={key}><span><b>{cognitiveNames[key]||key}</b><small>Level {levels[key]||1} / 5</small></span><strong>{value}%</strong><i><em style={{width:`${value}%`}}/></i></article>)}</div></section>}
    {details.processAnalysis&&<section className="process-analysis"><header><Gauge/><div><small>ПРОЦЕСС РЕШЕНИЯ</small><h2>{details.processAnalysis.label}</h2></div></header><div><span><b>{details.processAnalysis.accuracy}%</b><small>Точность</small></span><span><b>{(details.processAnalysis.averageResponseMs/1000).toFixed(1)} сек</b><small>Среднее время</small></span><span><b>{details.processAnalysis.answerChanges}</b><small>Смен ответов</small></span><span><b>{details.processAnalysis.timeouts}</b><small>Timeout</small></span></div></section>}
    {details.learningAnalysis&&<section className="learning-analysis"><header><Lightbulb/><div><small>АНАЛИЗ ОБУЧАЕМОСТИ</small><h2>Скорость обучения: {details.learningAnalysis.label}</h2></div></header><p>{details.learningAnalysis.explanation}</p></section>}
    {categoryEeg.length>0&&<section className="category-eeg"><header><Activity/><div><small>EEG ПО ТИПАМ ЗАДАЧ</small><h2>Где когнитивная работа была эффективнее</h2></div></header><div>{categoryEeg.map((item:any)=><article key={item.category}><b>{cognitiveNames[item.category]||item.category}</b><span>Внимание <strong>{item.attention}%</strong></span><span>Медитация <strong>{item.meditation}%</strong></span><span>Вовлечённость <strong>{item.engagement}%</strong></span><span>Фокус <strong>{item.focus}%</strong></span><span>Расслабление <strong>{item.relaxation}%</strong></span><span>Blink <strong>{item.blink}</strong></span><span>Сигнал <strong>{item.signal}%</strong></span></article>)}</div><p>Показатели описывают реакцию во время образовательных задач и не интерпретируются как активность «левого» или «правого» полушария.</p></section>}
    <div className="diagnostic-report-grid"><section><header><Target/><div><h3>Карта пробелов</h3><p>Навыки, которые стоит разобрать в первую очередь</p></div></header>{attempt.gaps.length?<div className="diagnostic-tags warning">{attempt.gaps.map((item:string)=><span key={item}>{item}</span>)}</div>:<div className="diagnostic-empty"><Check/>Критических пробелов не выявлено</div>}</section><section><header><Gauge/><div><h3>Сильные стороны</h3><p>На эти навыки можно опираться дальше</p></div></header>{attempt.strengths.length?<div className="diagnostic-tags success">{attempt.strengths.map((item:string)=><span key={item}>{item}</span>)}</div>:<div className="diagnostic-empty">Нужна дополнительная выборка заданий</div>}</section></div>
    <section className="recommendation-document"><header><FileText/><div><small>IUI EDUCATIONAL INSIGHT</small><h2>Персональный план рекомендаций</h2></div><button onClick={()=>window.print()}><Printer/>PDF</button></header><ol>{attempt.recommendations.map((item:string,index:number)=><li key={item}><i>{String(index+1).padStart(2,'0')}</i><p>{item}</p></li>)}</ol><footer><Lightbulb/><p><b>Важно:</b> результат используется для планирования обучения и не является медицинским заключением. Вывод подтверждается наблюдениями преподавателя и повторной диагностикой.</p></footer></section>
    {review.length>0&&<section className="answer-review"><header><FileText/><div><small>РАЗБОР ОТВЕТОВ</small><h2>Правильные ответы и объяснения</h2><p>Разбор доступен только после завершения всей диагностики.</p></div></header>{review.map((item:any)=><article className={item.correct?'correct':'incorrect'} key={item.questionId}><div><i>{item.number}</i><span><b>{item.question}</b><small>{cognitiveNames[item.category]||item.skill} · Level {item.difficulty}/5</small></span><em>{item.correct?'Правильно':'Неправильно'}</em></div><dl><div><dt>Ваш ответ</dt><dd>{item.studentAnswerText}</dd></div><div><dt>Правильный ответ</dt><dd>{item.correctAnswerText}</dd></div><div><dt>Время</dt><dd>{(item.responseTimeMs/1000).toFixed(1)} сек.</dd></div><div><dt>Изменений</dt><dd>{item.changes}</dd></div></dl><p><Lightbulb/>{item.explanation}</p></article>)}</section>}
  </div>;
}

export default function DiagnosticPage(){
  const [user,setUser]=useState<any>(null),[grade,setGrade]=useState(5),[gradeLocked,setGradeLocked]=useState(false),[language,setLanguage]=useState<'ru'|'kk'>('ru'),[questions,setQuestions]=useState<Question[]>([]),[section,setSection]=useState<Section>('math'),[index,setIndex]=useState(0),[answers,setAnswers]=useState<Record<string,number>>({}),[seconds,setSeconds]=useState(0),[startedAt,setStartedAt]=useState(''),[attempt,setAttempt]=useState<any>(null),[attempts,setAttempts]=useState<any[]>([]),[selected,setSelected]=useState<any>(null),[loading,setLoading]=useState(true),[adapting,setAdapting]=useState(false),[error,setError]=useState(''),[phase,setPhase]=useState(''),[device,setDevice]=useState<any>(bluetoothManager.getSnapshot().device),[latest,setLatest]=useState<EegSample|null>(null),[assessmentId,setAssessmentId]=useState(''),[useEeg,setUseEeg]=useState(false);
  const answersRef=useRef<Record<string,number>>({}),sessionRef=useRef(''),recordingRef=useRef(false),bufferRef=useRef<EegSample[]>([]),timelineRef=useRef<any[]>([]),submittingRef=useRef(false),questionStartedRef=useRef(''),questionSamplesRef=useRef<EegSample[]>([]),responseRef=useRef<any[]>([]),changesRef=useRef<Record<string,number>>({});
  useEffect(()=>{authApi.me().then(async({user})=>{setUser(user);if(user.role==='STUDENT'){try{const profile=await api<{students:any[]}>('/students');const className=profile.students[0]?.class?.name||'';const parsed=Number(className.match(/\d{1,2}/)?.[0]);if(parsed>=1&&parsed<=11){setGrade(parsed);setGradeLocked(true)}}catch{}}return api<{attempts:any[]}>('/diagnostics')}).then(result=>setAttempts(result.attempts)).catch(reason=>setError(reason.message)).finally(()=>setLoading(false))},[]);
  useEffect(()=>bluetoothManager.subscribe(snapshot=>setDevice(snapshot.device)),[]);
  useEffect(()=>bluetoothManager.subscribeSamples(sample=>{if(recordingRef.current){bufferRef.current.push(sample);questionSamplesRef.current.push(sample);setLatest(sample)}}),[]);
  const flush=async()=>{const batch=bufferRef.current.splice(0,500);if(!batch.length||!sessionRef.current)return;try{await api(`/sessions/${sessionRef.current}/samples`,{method:'POST',body:JSON.stringify({samples:batch})})}catch(reason){bufferRef.current.unshift(...batch);throw reason}};
  useEffect(()=>{if(!questions.length)return;const timer=window.setInterval(()=>void flush().catch(()=>{}),2000);return()=>window.clearInterval(timer)},[questions.length]);
  const currentQuestions=useMemo(()=>questions.filter(item=>item.section===section),[questions,section]),current=currentQuestions[index];

  const start=async()=>{setLoading(true);setError('');setPhase(useEeg?'Подключаем IUI NeuroBand':'Готовим задания');try{let connected:any=null;if(useEeg)connected=await bluetoothManager.connect();const test=await api<{questions:Question[];assessmentId:string}>(`/diagnostics/questions?grade=${grade}&language=${language}`);if(useEeg){setPhase('Создаём EEG-сессию');const created=await api<{session:{id:string}}>('/sessions',{method:'POST',body:JSON.stringify({deviceId:connected.id,subject:`Бесплатная когнитивная диагностика · ${grade} класс`})});sessionRef.current=created.session.id;setPhase('Калибровка сигнала · 3 секунды');await bluetoothManager.send('CALIBRATE');await new Promise(resolve=>window.setTimeout(resolve,3400));await bluetoothManager.send('START');recordingRef.current=true}else{sessionRef.current='';recordingRef.current=false}bufferRef.current=[];questionSamplesRef.current=[];responseRef.current=[];changesRef.current={};setLatest(null);setAssessmentId(test.assessmentId);setQuestions(test.questions);answersRef.current={};setAnswers({});setSection('math');setIndex(0);setSeconds(900);const now=new Date().toISOString();questionStartedRef.current=now;setStartedAt(now);timelineRef.current=[{section:'math',startedAt:now}];setAttempt(null)}catch(reason){if(sessionRef.current)void api(`/sessions/${sessionRef.current}`,{method:'DELETE'}).catch(()=>{});sessionRef.current='';recordingRef.current=false;setError(reason instanceof Error?reason.message:'Не удалось начать диагностику')}finally{setPhase('');setLoading(false)}};
  const submit=async()=>{if(submittingRef.current)return;submittingRef.current=true;setLoading(true);setPhase(sessionRef.current?'Завершаем EEG-анализ':'Сохраняем диагностику знаний');try{recordingRef.current=false;let eegSessionId=sessionRef.current||undefined;if(eegSessionId){await bluetoothManager.send('STOP').catch(()=>{});await flush();await api(`/sessions/${eegSessionId}/finish`,{method:'POST'})}const timeline=timelineRef.current.map((item,index,array)=>index===array.length-1&&!item.endedAt?{...item,endedAt:new Date().toISOString()}:item);setPhase('Формируем когнитивный отчёт');const payload:any={grade,language,answers:answersRef.current,startedAt,assessmentId,questionSnapshot:questions,responses:responseRef.current,sectionTimeline:timeline};if(eegSessionId)payload.eegSessionId=eegSessionId;const result=await api<{attempt:any}>('/diagnostics',{method:'POST',body:JSON.stringify(payload)});setAttempt(result.attempt);setQuestions([]);setAttempts(previous=>previous.some(item=>item.id===result.attempt.id)?previous:[result.attempt,...previous]);sessionRef.current=''}catch(reason){setError(reason instanceof Error?reason.message:'Не удалось сохранить диагностику')}finally{submittingRef.current=false;setPhase('');setLoading(false)}};
  const nextSection=()=>{const position=sectionOrder.indexOf(section),now=new Date().toISOString();timelineRef.current=timelineRef.current.map((item,index,array)=>index===array.length-1&&!item.endedAt?{...item,endedAt:now}:item);if(position===2){void submit();return}const next=sectionOrder[position+1];timelineRef.current.push({section:next,startedAt:now});setSection(next);setIndex(0);setSeconds(sectionInfo[next].minutes*60);questionStartedRef.current=now;questionSamplesRef.current=[]};
  const cancel=async()=>{if(!window.confirm('Прервать диагностику? Текущие ответы не будут сохранены.'))return;recordingRef.current=false;await bluetoothManager.send('STOP').catch(()=>{});if(sessionRef.current)await api(`/sessions/${sessionRef.current}`,{method:'DELETE'}).catch(()=>{});sessionRef.current='';bufferRef.current=[];timelineRef.current=[];answersRef.current={};setAnswers({});setQuestions([]);setLatest(null);setSeconds(0);setError('')};
  const captureResponse=(timeout=false)=>{if(!current||responseRef.current.some(item=>item.questionId===current.id))return;const endedAt=new Date().toISOString(),samples=questionSamplesRef.current,avg=(key:keyof EegSample)=>samples.length?Math.round(samples.reduce((sum,item)=>sum+Number(item[key]||0),0)/samples.length):0;responseRef.current.push({questionId:current.id,answer:answersRef.current[current.id]??null,responseTimeMs:Math.max(0,new Date(endedAt).getTime()-new Date(questionStartedRef.current||endedAt).getTime()),changes:changesRef.current[current.id]||0,timeout,startedAt:questionStartedRef.current,answeredAt:endedAt,eeg:{raw:avg('raw'),attention:avg('attention'),meditation:avg('meditation'),engagement:avg('engagement'),focus:avg('focus'),relaxation:avg('relaxation'),blink:avg('blink'),signal:avg('signal'),samples:samples.length}});questionSamplesRef.current=[];questionStartedRef.current=endedAt};
  const next=async()=>{captureResponse(false);if(index>=currentQuestions.length-1){nextSection();return}setAdapting(true);try{const remaining=currentQuestions.slice(index+1),adapted=await api<{nextQuestionId:string|null}>('/diagnostics/adapt',{method:'POST',body:JSON.stringify({grade,language,assessmentId,questionId:current.id,answer:answersRef.current[current.id],remainingIds:remaining.map(item=>item.id)})});if(adapted.nextQuestionId){setQuestions(all=>{const items=all.filter(item=>item.section===section),position=items.findIndex(item=>item.id===adapted.nextQuestionId);if(position<=index+1)return all;const reordered=[...items.slice(0,index+1),items[position],...items.slice(index+1,position),...items.slice(position+1)];let cursor=0;return all.map(item=>item.section===section?reordered[cursor++]:item)})}setIndex(value=>value+1)}catch{setIndex(value=>value+1)}finally{setAdapting(false)}};const choose=(id:string,value:number)=>{if(answersRef.current[id]!==undefined&&answersRef.current[id]!==value)changesRef.current[id]=(changesRef.current[id]||0)+1;answersRef.current={...answersRef.current,[id]:value};setAnswers(answersRef.current)};
  useEffect(()=>{if(!questions.length)return;const timer=window.setInterval(()=>setSeconds(value=>Math.max(0,value-1)),1000);return()=>window.clearInterval(timer)},[section,questions.length]);

  if(loading&&!questions.length)return <div className="loading-panel"><span className="loader dark-loader"/>{phase||'Загружаем диагностику...'}</div>;
  if(error&&!questions.length)return <><div className="page-head"><div><span>ДИАГНОСТИКА</span><h1>Проверка знаний и EEG</h1><p>Данные не потеряны: проверьте соединение и повторите действие.</p></div></div><div className="api-error" role="alert">{error}</div><button className="soft-button" onClick={()=>{setError('');setLoading(true);window.location.reload()}}><RefreshCw/>Повторить загрузку</button></>;
  if(user?.role!=='STUDENT')return <><div className="page-head"><div><span>БЕСПЛАТНЫЕ ПРОБНЫЕ ЗАНЯТИЯ</span><h1>Диагностика учеников</h1><p>Единый отчёт по знаниям и мозговой активности для планирования дальнейшей работы.</p></div></div>{selected?<><button className="diagnostic-back" onClick={()=>setSelected(null)}><ArrowLeft/>К списку результатов</button><Result attempt={selected}/></>:attempts.length?<div className="diagnostic-attempts">{attempts.map(item=><button key={item.id} onClick={()=>setSelected(item)}><div className="diagnostic-avatar">{item.student.firstName[0]}{item.student.lastName[0]}</div><span><b>{item.student.firstName} {item.student.lastName}</b><small>{item.student.class?.name||`${item.grade} класс`} · {item.eegSession?'EEG записан':'без EEG'} · {new Date(item.completedAt).toLocaleDateString('ru-RU')}</small></span><strong>{item.totalScore}%</strong><i><ArrowRight/></i></button>)}</div>:<div className="empty-analytics"><Brain/><h2>Диагностик пока нет</h2><p>После бесплатного пробного теста здесь появится документ знаний и EEG-рекомендаций.</p></div>}</>;
  if(attempt)return <><div className="page-head"><div><span>ПЕРСОНАЛЬНЫЙ РЕЗУЛЬТАТ</span><h1>Диагностика знаний и EEG</h1></div></div><Result attempt={attempt}/></>;
  if(!questions.length)return <><div className="page-head"><div><span>БЕСПЛАТНАЯ ПРОБНАЯ ДИАГНОСТИКА</span><h1>Знания и активность мозга</h1><p>Можно пройти обычную диагностику знаний без устройства или расширенную диагностику с IUI NeuroBand.</p></div></div><section className="diagnostic-intro"><div className="diagnostic-free">БЕСПЛАТНО · ПЕРВАЯ ДИАГНОСТИКА</div><div className="diagnostic-orbit"><Brain/><i/><i/></div><h2>Первый образовательный срез</h2><p>{useEeg?'Наденьте IUI NeuroBand. EEG будет записываться во время всех заданий, а преподаватель увидит реакцию на нагрузку.':'Устройство не требуется. Система сохранит знания, когнитивный профиль, пробелы и недельный план развития.'}</p><div className="diagnostic-config"><label>Режим диагностики<div><button className={!useEeg?'active':''} onClick={()=>setUseEeg(false)}><FileText/>Без устройства</button><button className={useEeg?'active':''} onClick={()=>setUseEeg(true)}><Bluetooth/>С NeuroBand</button></div></label></div>{useEeg&&<div className={`diagnostic-device ${device?'ready':''}`}><Bluetooth/><span><b>{device?`${device.name} подключён`:'NeuroBand подключится перед стартом'}</b><small>{device?`${device.serialNumber} · готов к записи`:'Браузер предложит выбрать устройство'}</small></span><i>{device?'ГОТОВО':'BLUETOOTH'}</i></div>}<div className="diagnostic-config"><label>Класс<select value={grade} disabled={gradeLocked} title={gradeLocked?'Класс определён по профилю ученика':''} onChange={event=>setGrade(Number(event.target.value))}>{Array.from({length:11},(_,i)=><option value={i+1} key={i+1}>{i+1} класс</option>)}</select>{gradeLocked&&<small>Определён по коду класса</small>}</label><label>Языковой блок<div><button className={language==='ru'?'active':''} onClick={()=>setLanguage('ru')}>Русский</button><button className={language==='kk'?'active':''} onClick={()=>setLanguage('kk')}>Қазақ тілі</button></div></label></div><div className="diagnostic-route">{sectionOrder.map(key=>{const info=sectionInfo[key],Icon=info.icon;return <article key={key}><Icon/><span><b>{key==='language'?(language==='kk'?'Қазақ тілі':'Русский язык'):info.title}</b><small>{info.minutes} минут{useEeg?' + EEG':''}</small></span></article>})}</div><button className="diagnostic-start" onClick={start}>{useEeg?<Bluetooth/>:<FileText/>}{useEeg?(device?'Начать диагностику с EEG':'Подключить NeuroBand и начать'):'Начать без устройства'}<ArrowRight/></button></section></>;
  const SectionIcon=sectionInfo[section].icon,progress=(sectionOrder.indexOf(section)+index/Math.max(1,currentQuestions.length))/3*100;
  const puzzleMode=['attention','memory','reaction','spatial','patterns','learning'].includes(current?.category||'')||isCreativeTask(current as any);
  return <div className="diagnostic-test"><header><div><SectionIcon/><span><small>БЛОК {sectionOrder.indexOf(section)+1} ИЗ 3 · {sessionRef.current?'EEG ЗАПИСЫВАЕТСЯ':'БЕЗ УСТРОЙСТВА'}</small><b>{section==='language'?(language==='kk'?'Қазақ тілі':'Русский язык'):sectionInfo[section].title}</b></span></div>{sessionRef.current&&<div className="diagnostic-live"><span><Activity/>Фокус {Math.round(latest?.focus||0)}%</span><span><Wifi/>Сигнал {Math.round(latest?.signal||0)}%</span></div>}<div className={seconds<60?'urgent':''}><Clock3/><b>{String(Math.floor(seconds/60)).padStart(2,'0')}:{String(seconds%60).padStart(2,'0')}</b></div></header>{latest&&latest.signal<40&&<div className="signal-warning"><Wifi/><span><b>Сигнал недостаточно устойчив</b><small>Поправьте электроды BioAmp EXG и постарайтесь меньше двигаться. Диагностика продолжится автоматически.</small></span></div>}<div className="diagnostic-progress"><i><em style={{width:`${progress}%`}}/></i><span>Вопрос {index+1} из {currentQuestions.length}</span></div><main className={puzzleMode?'puzzle-mode creative-diagnostic-mode':''}>{puzzleMode&&<div className="puzzle-orbit"><Brain/><i/><i/><i/></div>}<small>{puzzleMode?'COGNITIVE PUZZLE · ':''}{current?.skill}</small><h2>{current?.prompt}</h2>{isCreativeTask(current as any)?<CreativeTaskInteraction task={current as any} selected={answers[current.id]??null} setSelected={(value)=>choose(current.id,value)} feedback={null}/>:<div>{current?.options.map((option,optionIndex)=><button className={answers[current.id]===optionIndex?'selected':''} key={option} onClick={()=>choose(current.id,optionIndex)}><i>{String.fromCharCode(65+optionIndex)}</i><span>{option}</span>{answers[current.id]===optionIndex&&<Check/>}</button>)}</div>}</main><footer><div className="diagnostic-footer-actions"><button onClick={cancel} title="Прервать диагностику"><X/></button></div><span>{loading?'Сохраняем результат…':sessionRef.current?'EEG записывается автоматически':'Ответы сохранятся в профиль'}</span><button className="primary" disabled={answers[current.id]===undefined||loading||adapting} onClick={next}>{adapting?'Подбираем уровень…':loading?'Подождите…':index===currentQuestions.length-1?(section==='language'?'Завершить':'Следующий блок'):'Далее'}{!loading&&!adapting&&<ArrowRight/>}</button></footer></div>;
}
