import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { ArrowRight, Brain, Check, Flame, Sparkles, Target, Trophy, Zap } from 'lucide-react';
import { api } from './api';
import CelebrationOverlay from './CelebrationOverlay';
import './motivation-page.css';

const dayNames=['Пн','Вт','Ср','Чт','Пт','Сб','Вс'];
const iso=(date:Date)=>date.toISOString().slice(0,10);

export default function MotivationPage({onStart}:{onStart?:()=>void}){
  const [data,setData]=useState<any>(null);const [error,setError]=useState('');const [goal,setGoal]=useState(3);const [celebrate,setCelebrate]=useState(false);const [savingGoal,setSavingGoal]=useState(false);
  useEffect(()=>{api<any>('/motivation').then(response=>{setData(response);setGoal(response.student.weeklyGoal||3)}).catch(reason=>setError(reason.message))},[]);
  useEffect(()=>{const flame=document.querySelector('.hero-flame');flame?.classList.toggle('dormant',Boolean(data&&!data.student.streak))},[data]);
  const closeCelebration=useCallback(()=>setCelebrate(false),[]);
  const week=useMemo(()=>{const monday=new Date();monday.setHours(0,0,0,0);monday.setDate(monday.getDate()-((monday.getDay()+6)%7));return dayNames.map((name,index)=>{const date=new Date(monday);date.setDate(monday.getDate()+index);return{name,date,key:iso(date)}})},[]);
  useEffect(()=>{if(!data||data.weekSessions<goal)return;const key=`iui-goal-celebrated-${week[0].key}-${goal}`;if(!localStorage.getItem(key)){localStorage.setItem(key,'1');setCelebrate(true)}},[data,goal,week]);
  const setWeeklyGoal=async(value:number)=>{if(savingGoal)return;const previous=goal;setGoal(value);setSavingGoal(true);try{await api('/motivation/goal',{method:'PATCH',body:JSON.stringify({weeklyGoal:value})})}catch(reason){setGoal(previous);setError(reason instanceof Error?reason.message:'Не удалось сохранить цель')}finally{setSavingGoal(false)}};
  if(error)return <div className="api-error">{error}</div>;if(!data)return <div className="motivation-skeleton"><div/><div/><div/></div>;
  const percent=Math.min(100,Math.round(data.weekSessions/goal*100));const today=iso(new Date());
  return <>{celebrate&&<CelebrationOverlay title="Недельная цель выполнена!" message={`${data.weekSessions} занятий за неделю — отличный ритм. Серия укрепляется, а личная динамика становится точнее.`} eyebrow="ЦЕЛЬ ДОСТИГНУТА" onClose={closeCelebration}/>}<div className="page-head"><div><span>МОЙ РИТМ</span><h1>Мотивация</h1><p>Небольшие цели и регулярность без лишнего игрового давления.</p></div>{onStart&&<div className="page-actions"><button className="primary" onClick={onStart}><Zap/>Начать сессию</button></div>}</div><section className="motivation-hero-v2"><div className="hero-flame"><Flame fill="currentColor"/><i/><i/><i/></div><div><small>ТЕКУЩАЯ СЕРИЯ</small><h2>{data.student.streak} {data.student.streak===1?'день':'дней'} подряд</h2><p>{data.student.streak?'Огонь поддерживается завершёнными EEG-занятиями.':'Завершите занятие сегодня, чтобы зажечь серию.'}</p></div><div className="week-ring" style={{'--progress':`${percent*3.6}deg`} as React.CSSProperties}><span><b>{percent}%</b><small>цели</small></span></div></section><div className="motivation-layout"><section className="dash-card weekly-goal"><header><div><Target/><span><h3>Цель на неделю</h3><p>Выберите комфортный ритм</p></span></div><div className="goal-switch">{[3,5,7].map(value=><button key={value} className={goal===value?'active':''} onClick={()=>setWeeklyGoal(value)}>{value}</button>)}</div></header><div className="week-days">{week.map(day=>{const done=data.activeDates.includes(day.key);const current=day.key===today;return <div key={day.key} className={`${done?'done ':''}${current?'today':''}`}><i>{done?<Check/>:day.date.getDate()}</i><small>{day.name}</small></div>})}</div><div className="goal-progress"><span><b>{data.weekSessions} из {goal} занятий</b><small>{percent>=100?'Цель выполнена':`Осталось ${Math.max(0,goal-data.weekSessions)}`}</small></span><i><em style={{width:`${percent}%`}}/></i></div></section><section className="dash-card motivation-ai"><div className="motivation-ai-icon"><Brain/><Sparkles/></div><small>AI-МОТИВАЦИЯ</small><h3>{data.messages[0]}</h3><ul>{data.messages.slice(1).map((message:string)=><li key={message}><Check/>{message}</li>)}</ul>{onStart&&<button onClick={onStart}>Продолжить прогресс <ArrowRight/></button>}</section></div><section className="progress-level-strip"><div><Trophy/><span><small>LEVEL</small><b>{data.student.level}</b></span></div><i><em style={{width:`${(data.student.xp%500)/5}%`}}/></i><span><b>{data.student.xp} XP</b><small>{Math.max(0,data.student.level*500-data.student.xp)} до следующего уровня</small></span></section></>;
}
