import { useMemo, useState } from 'react';
import { Check, Clipboard, Heart, MessageCircle, Share2, Sparkles } from 'lucide-react';
import './parent-support-plan.css';

export default function ParentSupportPlan({plan,student,diagnostic}:{plan:any;student:any;diagnostic:any}){
  const [copied,setCopied]=useState(false);
  const focus=plan?.focusProfiles?.[0],today=plan?.availableDay||0,dayTasks=plan?.tasks?.filter((task:any)=>task.dayIndex===today)||[],done=dayTasks.filter((task:any)=>task.completedAt).length,finished=dayTasks.length>0&&done===dayTasks.length,completedDays=plan?.tasks?Array.from({length:7},(_,day)=>plan.tasks.filter((task:any)=>task.dayIndex===day)).filter((tasks:any[])=>tasks.length&&tasks.every(task=>task.completedAt)).length:0;
  const message=useMemo(()=>finished?`${student.firstName}, я заметил(а), что ты сегодня завершил(а) свой короткий план. Мне нравится, как ты не сдаёшься и проверяешь себя.`:`${student.firstName}, давай выберем удобные 10 минут для твоего задания. Я рядом, но решение попробуешь найти самостоятельно.`,[finished,student.firstName]);
  const actions=[{title:'Выберите время',text:finished?'Сегодняшняя практика уже выполнена. Не добавляйте новые задания.':'Предложите ребёнку два варианта времени, сохранив за ним выбор.',done:finished},{title:'Поддержите процесс',text:focus?.parentMessage||'Спросите, какая часть задания понятна, прежде чем подсказывать.',done:false},{title:'Завершите позитивно',text:'Отметьте конкретное действие: проверил ответ, объяснил ход решения или вернулся после ошибки.',done:false}];
  const copy=async()=>{await navigator.clipboard.writeText(message);setCopied(true);window.setTimeout(()=>setCopied(false),1800)};
  const share=async()=>{const text=`План IUI на сегодня для ${student.firstName}: ${dayTasks.length} заданий, около ${Math.max(7,dayTasks.length*3)} минут. Фокус: ${focus?.title||diagnostic?.gaps?.[0]||'закрепление навыка'}.`;if(navigator.share)await navigator.share({title:'План IUI',text});else{await navigator.clipboard.writeText(text);setCopied(true)}};
  return <section className="parent-support-plan"><header><div><small>СЕМЕЙНЫЙ ПЛАН НА СЕГОДНЯ</small><h3>Как помочь и не превратить занятие в контроль</h3><p>Три коротких действия, адаптированных под текущую неделю ребёнка.</p></div><button onClick={share}><Share2/>Поделиться</button></header><div className="parent-support-grid"><div className="parent-action-list">{actions.map((item,index)=><article className={item.done?'done':''} key={item.title}><i>{item.done?<Check/>:index+1}</i><span><b>{item.title}</b><p>{item.text}</p></span></article>)}</div><aside><Heart/><small>ГОТОВАЯ ФРАЗА РЕБЁНКУ</small><blockquote>«{message}»</blockquote><button onClick={copy}>{copied?<><Check/>Скопировано</>:<><Clipboard/>Скопировать фразу</>}</button></aside></div><footer><Sparkles/><span><b>Цель семьи на этой неделе</b><small>Поддержать регулярность и самостоятельное объяснение — не добиваться идеальных ответов с первой попытки.</small></span><em><MessageCircle/>{completedDays}/7 дней</em></footer></section>;
}
