import { useEffect, useState } from 'react';
import { ArrowRight, Brain, Check, Clock3, FileText, Flame, Heart, Sparkles, TrendingUp } from 'lucide-react';
import { api } from './api';
import './parent-overview.css';
import ParentSupportPlan from './ParentSupportPlan';

export default function ParentLearningOverview({user,setActive}:{user:any;setActive:(page:string)=>void}){
  const [plan,setPlan]=useState<any>(null),[student,setStudent]=useState<any>(null),[diagnostic,setDiagnostic]=useState<any>(null),[sessions,setSessions]=useState<any[]>([]),[loading,setLoading]=useState(true);
  useEffect(()=>{Promise.allSettled([api<any>('/homework-plan'),api<any>('/diagnostics'),api<any>('/reports')]).then(results=>{if(results[0].status==='fulfilled'){setPlan(results[0].value.plan);setStudent(results[0].value.student)}if(results[1].status==='fulfilled')setDiagnostic(results[1].value.attempts[0]||null);if(results[2].status==='fulfilled')setSessions(results[2].value.sessions||[])}).finally(()=>setLoading(false))},[]);
  if(loading)return <div className="student-overview-skeleton"><div/><section/><section/></div>;
  if(!student)return <div className="parent-home"><div className="page-head"><div><span>КАБИНЕТ РОДИТЕЛЯ</span><h1>Здравствуйте, {user.firstName}</h1><p>Профиль ребёнка появится после принятия приглашения преподавателя.</p></div></div><div className="empty-analytics"><Heart/><h2>Ожидаем привязку ребёнка</h2><p>Попросите преподавателя отправить приглашение на email вашего аккаунта.</p></div></div>;
  const today=plan?.availableDay||0,tasks=plan?.tasks?.filter((task:any)=>task.dayIndex===today)||[],todayDone=tasks.filter((task:any)=>task.completedAt).length,last=sessions[0];
  return <div className="parent-home"><div className="parent-head"><div><span>КАБИНЕТ РОДИТЕЛЯ</span><h1>{student.firstName}: неделя в фокусе</h1><p>Главное без лишних цифр: регулярность, сильные стороны и где нужна спокойная поддержка.</p></div><button onClick={()=>setActive('Учебный отчёт')}><FileText/>Полный отчёт<ArrowRight/></button></div><section className="parent-week-hero"><div><small>ПРОГРЕСС НЕДЕЛИ</small><h2>{plan?.progress||0}%</h2><p>{plan?`${plan.tasks.filter((task:any)=>task.completedAt).length} из ${plan.tasks.length} микро-заданий выполнено`:'План появится после диагностики'}</p><i><em style={{width:`${plan?.progress||0}%`}}/></i></div><div className="parent-today"><span className={todayDone===tasks.length&&tasks.length?'done':''}>{todayDone===tasks.length&&tasks.length?<Check/>:<Clock3/>}</span><div><small>СЕГОДНЯ</small><b>{tasks.length?`${todayDone}/${tasks.length} заданий`:'Нет задания'}</b><p>{todayDone===tasks.length&&tasks.length?'Дневная цель выполнена — похвалите за регулярность.':'Лучше мягко напомнить, но не контролировать каждый ответ.'}</p></div></div></section><div className="parent-kpis"><article><Flame/><span><b>{student.streak||0} дней</b><small>текущая серия</small></span></article><article><Brain/><span><b>{diagnostic?.totalScore??'—'}{diagnostic?'%':''}</b><small>стартовая диагностика</small></span></article><article><TrendingUp/><span><b>{last?.focus??'—'}{last?'%':''}</b><small>последний EEG-фокус</small></span></article><article><Sparkles/><span><b>Level {student.level||1}</b><small>{student.xp||0} XP накоплено</small></span></article></div><div className="parent-columns"><section><header><h3>Что сейчас развиваем</h3><button onClick={()=>setActive('Мой план')}>План <ArrowRight/></button></header><div className="parent-skills">{(plan?.focusSkills||diagnostic?.gaps||[]).slice(0,4).map((skill:string,index:number)=><span key={skill}><i>{index+1}</i><b>{skill}</b></span>)}{!plan&&!diagnostic&&<p>После первой диагностики здесь появятся персональные навыки.</p>}</div></section><section className="parent-coach"><Heart/><small>КАК ПОДДЕРЖАТЬ СЕГОДНЯ</small><h3>{todayDone===tasks.length&&tasks.length?'Заметьте усилие, а не только результат':'Предложите выбрать удобные 10 минут'}</h3><p>{todayDone===tasks.length&&tasks.length?'Скажите: «Я вижу, что ты не пропустил занятие». Такая обратная связь поддерживает самостоятельность.':'Не подсказывайте правильный вариант сразу. Лучше спросите, какая часть задания кажется непонятной.'}</p></section></div><ParentSupportPlan plan={plan} student={student} diagnostic={diagnostic}/>{diagnostic&&<section className="parent-recommendation"><Sparkles/><div><small>РЕКОМЕНДАЦИЯ IUI</small><h3>Следующий полезный шаг</h3><p>{plan?.focusProfiles?.[0]?.parentMessage||diagnostic.recommendations?.[0]||"Продолжайте короткие регулярные занятия."}</p></div><button onClick={()=>setActive('Учебный отчёт')}>Все рекомендации <ArrowRight/></button></section>}</div>;
}
