import { useEffect, useState } from 'react';
import { ArrowRight, Brain, Building2, CheckCircle2, Download, FileText, Sparkles, Target, TrendingUp, Users } from 'lucide-react';
import { api } from './api';
import './school-impact.css';

const signed=(value:number)=>`${value>=0?'+':''}${value}%`;

export default function SchoolImpactPage(){
  const [data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
  useEffect(()=>{api<any>('/impact-dashboard').then(setData).catch(reason=>setError(reason.message)).finally(()=>setLoading(false))},[]);
  const csv=()=>{if(!data)return;const rows=[['Класс','Ученики','Диагностировано','План','Фокус','Вовлечённость'],...data.classes.map((item:any)=>[item.name,item.students,item.diagnosed,`${item.planProgress}%`,`${item.focus}%`,`${item.engagement}%`])];const content=rows.map((row:any[])=>row.map(value=>`"${String(value).replace(/"/g,'""')}"`).join(',')).join('\n');const link=document.createElement('a');link.href=URL.createObjectURL(new Blob(['\ufeff'+content],{type:'text/csv;charset=utf-8'}));link.download='iui-school-impact.csv';link.click();setTimeout(()=>URL.revokeObjectURL(link.href),500)};
  if(loading)return <div className="impact-skeleton"><div/><section/><section/></div>;
  if(error)return <div className="api-error">{error}</div>;
  const k=data.kpis,funnel=[['Все ученики',data.funnel.students],['Диагностика',data.funnel.diagnosed],['Недельная практика',data.funnel.practicing],['Контроль',data.funnel.checked],['Отчёт',data.funnel.reports]],max=Math.max(1,data.funnel.students);
  return <div className="school-impact">
    <div className="page-head"><div><span>ЭФФЕКТ IUI · ПОСЛЕДНИЕ {data.period.toUpperCase()}</span><h1>Ценность для школы</h1><p>Охват, учебная динамика и доказательства работы программы — без ручного сведения таблиц.</p></div><div className="page-actions"><button className="soft-button" onClick={csv}><Download/>CSV</button><button className="primary" onClick={()=>window.print()}><FileText/>Отчёт администрации</button></div></div>
    <section className="impact-hero"><div><small>ОБРАЗОВАТЕЛЬНЫЙ ОХВАТ</small><h2>{k.coverage}%</h2><p>{data.funnel.diagnosed} из {k.students} учеников уже имеют персональную точку старта.</p><i><em style={{width:`${k.coverage}%`}}/></i></div><div className="impact-hero-metrics"><span><TrendingUp/><b>{signed(k.knowledgeDelta)}</b><small>динамика знаний</small></span><span><Brain/><b>{signed(k.focusDelta)}</b><small>динамика фокуса</small></span><span><Target/><b>{k.planCompletion}%</b><small>выполнение планов</small></span></div></section>
    <div className="impact-kpis"><article><Users/><span><b>{k.students}</b><small>учеников в программе</small></span></article><article><CheckCircle2/><span><b>{k.active}</b><small>занимались между встречами</small></span></article><article><Target/><span><b>{k.accuracy}%</b><small>точность микропрактики</small></span></article><article><FileText/><span><b>{k.parentReports}</b><small>отчётов для семей</small></span></article></div>
    <div className="impact-layout"><section className="impact-funnel"><header><div><h3>Воронка программы</h3><p>Где школа теряет охват и кому требуется напоминание</p></div><Sparkles/></header><div>{funnel.map(([label,value]:any,index)=><article key={label}><span><b>{label}</b><small>{value} учеников</small></span><i><em style={{width:`${value/max*100}%`}}/></i><strong>{index?`${Math.round(value/Math.max(1,funnel[index-1][1] as number)*100)}%`:'100%'}</strong></article>)}</div></section><section className="impact-evidence"><header><h3>Доказательства использования</h3><p>Фактическая активность за период</p></header><div>{data.evidence.map((item:any,index:number)=><article key={item.label}><i>{String(index+1).padStart(2,'0')}</i><span><b>{item.value}</b><small>{item.label}</small></span></article>)}</div></section></div>
    <section className="impact-classes"><header><div><h3>Классы и группы</h3><p>Сравнение охвата и регулярности — не рейтинг детей.</p></div><span><Building2/>{data.classes.length} групп</span></header><div className="impact-table"><div className="impact-row head"><span>Класс</span><span>Охват</span><span>Недельный план</span><span>Фокус EEG</span><span>Вовлечённость</span></div>{data.classes.map((item:any)=><div className="impact-row" key={item.id}><span><b>{item.name}</b><small>{item.students} учеников</small></span><span><b>{item.diagnosed}/{item.students}</b><small>диагностика</small></span><span><i><em style={{width:`${item.planProgress}%`}}/></i><b>{item.planProgress}%</b></span><span><b>{item.focus||'—'}{item.focus?'%':''}</b></span><span><b>{item.engagement||'—'}{item.engagement?'%':''}</b></span></div>)}</div></section>
    <section className="impact-actions"><header><div><h3>Следующие управленческие действия</h3><p>IUI автоматически превращает данные в конкретный список.</p></div><ArrowRight/></header><div>{data.needSupport.length?data.needSupport.map((item:any)=><article key={item.id}><span><b>{item.name}</b><small>{item.publicId}</small></span><p>{item.reason}</p><em>Связаться с семьёй</em></article>):<div className="impact-clear"><CheckCircle2/><span><b>Критичных действий нет</b><small>Продолжайте текущий ритм программы.</small></span></div>}</div></section>
  </div>;
}
