import { useEffect, useMemo, useState } from 'react';
import { Activity, ArrowRight, Brain, Check, Filter, Flame, Search, Target, TrendingUp, Users, X } from 'lucide-react';
import { api } from './api';
import './teacher-homework.css';
import './teacher-checkpoint.css';

const navigate=(page:string)=>{const button=[...document.querySelectorAll<HTMLButtonElement>('.app-side nav button')].find(item=>item.textContent?.includes(page));button?.click()};
const signed=(value:number)=>`${value>=0?'+':''}${value}%`;

export default function TeacherHomeworkOverview(){
  const [students,setStudents]=useState<any[]>([]),[selected,setSelected]=useState<any>(null),[query,setQuery]=useState(''),[status,setStatus]=useState('Все'),[loading,setLoading]=useState(true),[error,setError]=useState('');
  useEffect(()=>{api<{students:any[]}>('/homework-overview').then(result=>setStudents(result.students)).catch(reason=>setError(reason.message)).finally(()=>setLoading(false))},[]);
  const category=(student:any)=>!student.plan?'Без диагностики':student.plan.status==='COMPLETED'?'Ждёт диагностику':student.plan.checkIn?'Контроль пройден':student.plan.progress<25?'Нужна поддержка':student.plan.progress>=75?'Высокий прогресс':'В процессе';
  const filtered=useMemo(()=>students.filter(student=>`${student.firstName} ${student.lastName} ${student.class?.name||''}`.toLowerCase().includes(query.toLowerCase())&&(status==='Все'||category(student)===status)),[students,query,status]);
  if(loading)return <div className="loading-panel"><span className="loader dark-loader"/>Загружаем недельные планы...</div>;
  const active=students.filter(item=>item.plan?.status==='ACTIVE'),average=active.length?Math.round(active.reduce((sum,item)=>sum+item.plan.progress,0)/active.length):0,support=active.filter(item=>item.plan.progress<25),checked=active.filter(item=>item.plan.checkIn);
  return <>
    <div className="page-head"><div><span>СОПРОВОЖДЕНИЕ МЕЖДУ ДИАГНОСТИКАМИ</span><h1>Недельные планы</h1><p>Понимайте, кто работает регулярно, как изменились знания и где нужна помощь.</p></div><div className="page-actions"><button className="primary" onClick={()=>navigate('Учебный отчёт')}><TrendingUp/>Учебные отчёты</button></div></div>
    {error&&<div className="api-error">{error}</div>}
    <div className="teacher-plan-kpis"><article><Users/><span><b>{active.length}</b><small>активных планов</small></span></article><article><TrendingUp/><span><b>{average}%</b><small>средний прогресс</small></span></article><article><Activity/><span><b>{checked.length}</b><small>контроль пройден</small></span></article><article className={support.length?'attention':''}><Target/><span><b>{support.length}</b><small>нужна поддержка</small></span></article></div>
    <div className="teacher-plan-toolbar"><label><Search/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Имя ученика или класс..."/></label><div><Filter/><select value={status} onChange={event=>setStatus(event.target.value)}><option>Все</option><option>В процессе</option><option>Контроль пройден</option><option>Высокий прогресс</option><option>Нужна поддержка</option><option>Без диагностики</option><option>Ждёт диагностику</option></select></div></div>
    <div className="teacher-plan-table"><header><span>Ученик</span><span>Персональный фокус</span><span>Неделя</span><span>Серия</span><span>Статус</span><span/></header>{filtered.map((student,index)=><button key={student.id} onClick={()=>setSelected(student)}><span className="plan-student"><i className={`av${index%3}`}>{student.firstName[0]}{student.lastName[0]}</i><em><b>{student.firstName} {student.lastName}</b><small>{student.class?.name||'Без класса'} · {student.publicId}</small></em></span><span className="plan-focus">{student.plan?(student.plan.focusSkills as string[]).slice(0,2).join(' · ')||'Закрепление базы':'Ожидает диагностику'}</span><span className="plan-bar"><i><em style={{width:`${student.plan?.progress||0}%`}}/></i><b>{student.plan?.progress||0}%</b></span><span className="plan-streak"><Flame/>{student.streak} дн.</span><span className={`plan-state ${!student.plan?'new':student.plan.checkIn?'great':student.plan.progress<25?'risk':student.plan.progress>=75?'great':'active'}`}>{!student.plan?'Не начато':student.plan.status==='COMPLETED'?'Новая диагностика':student.plan.checkIn?`Контроль ${student.plan.checkIn.totalScore}%`:student.plan.progress<25?'Поддержать':student.plan.progress>=75?'Отлично':'В процессе'}</span><ArrowRight/></button>)}</div>
    {!filtered.length&&<div className="empty-analytics"><Search/><h2>Ничего не найдено</h2><p>Измените поиск или фильтр состояния.</p></div>}
    {selected&&<div className="plan-drawer-backdrop" onMouseDown={()=>setSelected(null)}><aside className="plan-drawer" onMouseDown={event=>event.stopPropagation()}>
      <header><div className="plan-drawer-avatar">{selected.firstName[0]}{selected.lastName[0]}</div><div><small>НЕДЕЛЬНОЕ СОПРОВОЖДЕНИЕ</small><h2>{selected.firstName} {selected.lastName}</h2><p>{selected.class?.name||'Без класса'} · Level {selected.level}</p></div><button onClick={()=>setSelected(null)}><X/></button></header>
      {selected.plan?<><section className="drawer-progress"><div><span><b>{selected.plan.progress}%</b><small>выполнено</small></span><span><b>{selected.plan.completedDays}/7</b><small>учебных дней</small></span><span><b>{selected.streak}</b><small>дней серии</small></span></div><i><em style={{width:`${selected.plan.progress}%`}}/></i></section>
        {selected.plan.checkIn?<section className="teacher-checkpoint-result"><Brain/><div><small>КОНТРОЛЬНАЯ ТОЧКА ПРОЙДЕНА</small><h3>{selected.plan.checkIn.totalScore}% · {signed(selected.plan.checkIn.baselineDelta)} к старту</h3><p>{selected.plan.checkIn.recommendation}</p><span>Фокус {signed(selected.plan.checkIn.focusDelta)} · вовлечённость {signed(selected.plan.checkIn.engagementDelta)} · адаптировано {selected.plan.checkIn.adaptedTaskCount}</span></div></section>:<section className="teacher-checkpoint-wait"><Activity/><div><small>КОНТРОЛЬНАЯ ТОЧКА</small><h3>Ожидает прохождения ребёнком</h3><p>Откроется после двух завершённых дней или в четвёртый день плана.</p></div></section>}
        <section className="drawer-focus"><Brain/><div><small>НАВЫКИ В РАБОТЕ</small><h3>{(selected.plan.focusSkills as string[]).join(' · ')||'Закрепление базовых навыков'}</h3><p>{selected.plan.checkIn?'План уже обновлён по результату контрольной точки.':'План создан по первой диагностике ученика.'}</p></div></section>
        <section className="drawer-week"><h3>Прогресс семи дней</h3><div>{Array.from({length:7},(_,day)=><span className={day<selected.plan.completedDays?'done':''} key={day}>{day<selected.plan.completedDays?<Check/>:day+1}<small>Д{day+1}</small></span>)}</div></section>
        <div className="drawer-actions"><button onClick={()=>navigate('Учебный отчёт')}><TrendingUp/>Открыть полный отчёт</button><p>{selected.plan.status==='COMPLETED'?'Неделя завершена. При следующей встрече проведите новую диагностику.':selected.plan.checkIn?'Сравнение сохранено. Наблюдайте, как ребёнок справляется с обновлёнными заданиями.':selected.plan.progress<25?'Помогите родителю выбрать удобное время для коротких занятий.':'Продолжайте наблюдение: ребёнок движется по персональному маршруту.'}</p></div>
      </>:<section className="drawer-empty"><Brain/><h3>Нет стартовой диагностики</h3><p>План появится автоматически, когда ученик пройдёт первую диагностику знаний с EEG.</p></section>}
    </aside></div>}
  </>;
}
